# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom_commands.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont,QFontDatabase

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 729)
        MainWindow.setMinimumSize(QtCore.QSize(400, 0))
        MainWindow.setMaximumSize(QtCore.QSize(100000, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QFontDatabase.addApplicationFont(':/Fonts/orbitron.light.ttf')
        QFontDatabase.addApplicationFont(':/Fonts/pdark.ttf')
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("border-image: url(:/Settings_window/personal_info_background.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 35)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("border-image:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.heading = QtWidgets.QLabel(self.frame_2)
        self.heading.setStyleSheet("color:white;\n"
"font: 25 37px \"Orbitron\";")
        self.heading.setAlignment(QtCore.Qt.AlignCenter)
        self.heading.setObjectName("heading")
        self.horizontalLayout.addWidget(self.heading)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setStyleSheet("border-image:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(-1, 35, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.information = QtWidgets.QLabel(self.frame)
        self.information.setStyleSheet("font: 16px \"Orbitron\";\n"
"color:white;\n"
"background-color:transparent;")
        self.information.setAlignment(QtCore.Qt.AlignCenter)
        self.information.setObjectName("information")
        self.horizontalLayout_2.addWidget(self.information)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.body = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.body.sizePolicy().hasHeightForWidth())
        self.body.setSizePolicy(sizePolicy)
        self.body.setMinimumSize(QtCore.QSize(0, 40))
        self.body.setStyleSheet("border-image:none;")
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.gridLayout = QtWidgets.QGridLayout(self.body)
        self.gridLayout.setContentsMargins(34, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.r8 = QtWidgets.QLineEdit(self.body)
        self.r8.setMinimumSize(QtCore.QSize(0, 50))
        self.r8.setMaximumSize(QtCore.QSize(284, 16777215))
        self.r8.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 11pt \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.r8.setAlignment(QtCore.Qt.AlignCenter)
        self.r8.setObjectName("r8")
        self.gridLayout.addWidget(self.r8, 7, 2, 1, 1)
        self.q3 = QtWidgets.QLineEdit(self.body)
        self.q3.setMinimumSize(QtCore.QSize(0, 55))
        self.q3.setMaximumSize(QtCore.QSize(400, 16777215))
        self.q3.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"orbitron\";\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"border-image: url(:/miccel/border_element.png);")
        self.q3.setAlignment(QtCore.Qt.AlignCenter)
        self.q3.setObjectName("q3")
        self.gridLayout.addWidget(self.q3, 2, 0, 1, 1)
        self.r3 = QtWidgets.QLineEdit(self.body)
        self.r3.setMinimumSize(QtCore.QSize(0, 50))
        self.r3.setMaximumSize(QtCore.QSize(284, 16777215))
        self.r3.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 11pt \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.r3.setAlignment(QtCore.Qt.AlignCenter)
        self.r3.setObjectName("r3")
        self.gridLayout.addWidget(self.r3, 2, 2, 1, 1)
        self.q6 = QtWidgets.QLineEdit(self.body)
        self.q6.setMinimumSize(QtCore.QSize(0, 55))
        self.q6.setMaximumSize(QtCore.QSize(400, 16777215))
        self.q6.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"orbitron\";\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"border-image: url(:/miccel/border_element.png);")
        self.q6.setAlignment(QtCore.Qt.AlignCenter)
        self.q6.setObjectName("q6")
        self.gridLayout.addWidget(self.q6, 5, 0, 1, 1)
        self.r1 = QtWidgets.QLineEdit(self.body)
        self.r1.setMinimumSize(QtCore.QSize(0, 50))
        self.r1.setMaximumSize(QtCore.QSize(284, 16777215))
        self.r1.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 11pt \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.r1.setAlignment(QtCore.Qt.AlignCenter)
        self.r1.setObjectName("r1")
        self.gridLayout.addWidget(self.r1, 0, 2, 1, 1)
        self.r2 = QtWidgets.QLineEdit(self.body)
        self.r2.setMinimumSize(QtCore.QSize(0, 50))
        self.r2.setMaximumSize(QtCore.QSize(284, 16777215))
        self.r2.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 11pt \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.r2.setAlignment(QtCore.Qt.AlignCenter)
        self.r2.setObjectName("r2")
        self.gridLayout.addWidget(self.r2, 1, 2, 1, 1)
        self.r7 = QtWidgets.QLineEdit(self.body)
        self.r7.setMinimumSize(QtCore.QSize(0, 50))
        self.r7.setMaximumSize(QtCore.QSize(284, 16777215))
        self.r7.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 11pt \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.r7.setAlignment(QtCore.Qt.AlignCenter)
        self.r7.setObjectName("r7")
        self.gridLayout.addWidget(self.r7, 6, 2, 1, 1)
        self.q2 = QtWidgets.QLineEdit(self.body)
        self.q2.setMinimumSize(QtCore.QSize(0, 55))
        self.q2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.q2.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"orbitron\";\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"border-image: url(:/miccel/border_element.png);")
        self.q2.setAlignment(QtCore.Qt.AlignCenter)
        self.q2.setObjectName("q2")
        self.gridLayout.addWidget(self.q2, 1, 0, 1, 1)
        self.q7 = QtWidgets.QLineEdit(self.body)
        self.q7.setMinimumSize(QtCore.QSize(0, 55))
        self.q7.setMaximumSize(QtCore.QSize(400, 16777215))
        self.q7.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"orbitron\";\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"border-image: url(:/miccel/border_element.png);")
        self.q7.setAlignment(QtCore.Qt.AlignCenter)
        self.q7.setObjectName("q7")
        self.gridLayout.addWidget(self.q7, 6, 0, 1, 1)
        self.q4 = QtWidgets.QLineEdit(self.body)
        self.q4.setMinimumSize(QtCore.QSize(0, 55))
        self.q4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.q4.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"orbitron\";\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"border-image: url(:/miccel/border_element.png);")
        self.q4.setAlignment(QtCore.Qt.AlignCenter)
        self.q4.setObjectName("q4")
        self.gridLayout.addWidget(self.q4, 3, 0, 1, 1)
        self.q8 = QtWidgets.QLineEdit(self.body)
        self.q8.setMinimumSize(QtCore.QSize(0, 55))
        self.q8.setMaximumSize(QtCore.QSize(400, 16777215))
        self.q8.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"orbitron\";\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"border-image: url(:/miccel/border_element.png);")
        self.q8.setAlignment(QtCore.Qt.AlignCenter)
        self.q8.setObjectName("q8")
        self.gridLayout.addWidget(self.q8, 7, 0, 1, 1)
        self.q5 = QtWidgets.QLineEdit(self.body)
        self.q5.setMinimumSize(QtCore.QSize(0, 55))
        self.q5.setMaximumSize(QtCore.QSize(400, 16777215))
        self.q5.setStyleSheet("border-image: url(:/miccel/border_element.png);\n"
"color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"Orbitron\";")
        self.q5.setAlignment(QtCore.Qt.AlignCenter)
        self.q5.setObjectName("q5")
        self.gridLayout.addWidget(self.q5, 4, 0, 1, 1)
        self.r5 = QtWidgets.QLineEdit(self.body)
        self.r5.setMinimumSize(QtCore.QSize(0, 50))
        self.r5.setMaximumSize(QtCore.QSize(284, 16777215))
        self.r5.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 11pt \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.r5.setAlignment(QtCore.Qt.AlignCenter)
        self.r5.setObjectName("r5")
        self.gridLayout.addWidget(self.r5, 4, 2, 1, 1)
        self.q1 = QtWidgets.QLineEdit(self.body)
        self.q1.setMinimumSize(QtCore.QSize(0, 55))
        self.q1.setMaximumSize(QtCore.QSize(401, 16777215))
        self.q1.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"orbitron\";\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"border-image: url(:/miccel/border_element.png);")
        self.q1.setAlignment(QtCore.Qt.AlignCenter)
        self.q1.setObjectName("q1")
        self.gridLayout.addWidget(self.q1, 0, 0, 1, 1)
        self.r4 = QtWidgets.QLineEdit(self.body)
        self.r4.setMinimumSize(QtCore.QSize(0, 50))
        self.r4.setMaximumSize(QtCore.QSize(284, 16777215))
        self.r4.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 11pt \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.r4.setAlignment(QtCore.Qt.AlignCenter)
        self.r4.setObjectName("r4")
        self.gridLayout.addWidget(self.r4, 3, 2, 1, 1)
        self.r6 = QtWidgets.QLineEdit(self.body)
        self.r6.setMinimumSize(QtCore.QSize(0, 50))
        self.r6.setMaximumSize(QtCore.QSize(284, 16777215))
        self.r6.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 11pt \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.r6.setAlignment(QtCore.Qt.AlignCenter)
        self.r6.setObjectName("r6")
        self.gridLayout.addWidget(self.r6, 5, 2, 1, 1)
        self.verticalLayout.addWidget(self.body)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 93))
        self.frame_4.setStyleSheet("border-image:none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setContentsMargins(372, 0, -1, 15)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(26)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.back = QtWidgets.QPushButton(self.frame_4)
        self.back.setMinimumSize(QtCore.QSize(0, 77))
        self.back.setMaximumSize(QtCore.QSize(257, 16777215))
        self.back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.back.setAutoFillBackground(False)
        self.back.setStyleSheet("QPushButton{\n"
"background-image: url(:/buttons/close_button.png);\n"
"border:none;\n"
"background-repeat:no-repeat;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid transparent;;\n"
"}")
        self.back.setText("")
        self.back.setObjectName("back")
        self.gridLayout_2.addWidget(self.back, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Custom commands"))
        self.heading.setText(_translate("MainWindow", "Custom Commands"))
        self.information.setText(_translate("MainWindow", "You can ask custom queries to the A.I and make it reply the answer you want"))
        self.r8.setPlaceholderText(_translate("MainWindow", "Reply"))
        self.q3.setPlaceholderText(_translate("MainWindow", "Your Query"))
        self.r3.setPlaceholderText(_translate("MainWindow", "Reply"))
        self.q6.setPlaceholderText(_translate("MainWindow", "Your Query"))
        self.r1.setPlaceholderText(_translate("MainWindow", "Reply"))
        self.r2.setPlaceholderText(_translate("MainWindow", "Reply"))
        self.r7.setPlaceholderText(_translate("MainWindow", "Reply"))
        self.q2.setPlaceholderText(_translate("MainWindow", "Your Query"))
        self.q7.setPlaceholderText(_translate("MainWindow", "Your Query"))
        self.q4.setPlaceholderText(_translate("MainWindow", "Your Query"))
        self.q8.setPlaceholderText(_translate("MainWindow", "Your Query"))
        self.q5.setPlaceholderText(_translate("MainWindow", "Your Query"))
        self.r5.setPlaceholderText(_translate("MainWindow", "Reply"))
        self.q1.setPlaceholderText(_translate("MainWindow", "Your Query"))
        self.r4.setPlaceholderText(_translate("MainWindow", "Reply"))
        self.r6.setPlaceholderText(_translate("MainWindow", "Reply"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
