# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_location.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont,QFontDatabase

class Ui_file_location(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 651)
        MainWindow.setMinimumSize(QtCore.QSize(400, 0))
        MainWindow.setMaximumSize(QtCore.QSize(100000, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        QFontDatabase.addApplicationFont(':/Fonts/orbitron.light.ttf')
        QFontDatabase.addApplicationFont(':/Fonts/pdark.ttf')
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("border-image: url(:/Settings_window/personal_info_background.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 35)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("border-image:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("color:white;\n"
"font: 25 37px \"Orbitron\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setStyleSheet("border-image:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(-1, 27, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.heading = QtWidgets.QLabel(self.frame)
        self.heading.setStyleSheet("font: 22px \"Orbitron\";\n"
"color:white;\n"
"background-color:transparent;")
        self.heading.setAlignment(QtCore.Qt.AlignCenter)
        self.heading.setObjectName("heading")
        self.horizontalLayout_2.addWidget(self.heading)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setStyleSheet("border-image:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setContentsMargins(34, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.f7 = QtWidgets.QLineEdit(self.frame_3)
        self.f7.setMinimumSize(QtCore.QSize(0, 55))
        self.f7.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f7.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 15px \"orbitron\";\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"border-image: url(:/miccel/border_element.png);")
        self.f7.setAlignment(QtCore.Qt.AlignCenter)
        self.f7.setObjectName("f7")
        self.gridLayout.addWidget(self.f7, 6, 0, 1, 1)
        self.f2 = QtWidgets.QLineEdit(self.frame_3)
        self.f2.setMinimumSize(QtCore.QSize(0, 55))
        self.f2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f2.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 15px \"orbitron\";\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"border-image: url(:/miccel/border_element.png);")
        self.f2.setAlignment(QtCore.Qt.AlignCenter)
        self.f2.setObjectName("f2")
        self.gridLayout.addWidget(self.f2, 1, 0, 1, 1)
        self.f3 = QtWidgets.QLineEdit(self.frame_3)
        self.f3.setMinimumSize(QtCore.QSize(0, 55))
        self.f3.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f3.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 15px \"orbitron\";\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"border-image: url(:/miccel/border_element.png);")
        self.f3.setAlignment(QtCore.Qt.AlignCenter)
        self.f3.setObjectName("f3")
        self.gridLayout.addWidget(self.f3, 2, 0, 1, 1)
        self.n7 = QtWidgets.QLineEdit(self.frame_3)
        self.n7.setMinimumSize(QtCore.QSize(0, 50))
        self.n7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n7.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 19px \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.n7.setAlignment(QtCore.Qt.AlignCenter)
        self.n7.setObjectName("n7")
        self.gridLayout.addWidget(self.n7, 6, 3, 1, 1)
        self.t7 = QtWidgets.QToolButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t7.sizePolicy().hasHeightForWidth())
        self.t7.setSizePolicy(sizePolicy)
        self.t7.setMinimumSize(QtCore.QSize(0, 30))
        self.t7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.t7.setStyleSheet("color:white;\n"
"border-image: url(:/miccel/border_element.png);\n"
"border:none;\n"
"font: 14pt \"Orbitron\";")
        self.t7.setObjectName("t7")
        self.gridLayout.addWidget(self.t7, 6, 1, 1, 1)
        self.f4 = QtWidgets.QLineEdit(self.frame_3)
        self.f4.setMinimumSize(QtCore.QSize(0, 55))
        self.f4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f4.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 15px \"orbitron\";\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"border-image: url(:/miccel/border_element.png);")
        self.f4.setAlignment(QtCore.Qt.AlignCenter)
        self.f4.setObjectName("f4")
        self.gridLayout.addWidget(self.f4, 3, 0, 1, 1)
        self.f8 = QtWidgets.QLineEdit(self.frame_3)
        self.f8.setMinimumSize(QtCore.QSize(0, 55))
        self.f8.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f8.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 15px \"orbitron\";\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"border-image: url(:/miccel/border_element.png);")
        self.f8.setAlignment(QtCore.Qt.AlignCenter)
        self.f8.setObjectName("f8")
        self.gridLayout.addWidget(self.f8, 7, 0, 1, 1)
        self.t1 = QtWidgets.QToolButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1.sizePolicy().hasHeightForWidth())
        self.t1.setSizePolicy(sizePolicy)
        self.t1.setMinimumSize(QtCore.QSize(0, 30))
        self.t1.setMaximumSize(QtCore.QSize(47, 16777215))
        self.t1.setStyleSheet("color:white;\n"
"border-image: url(:/miccel/border_element.png);\n"
"border:none;\n"
"font: 14pt \"Orbitron\";\n"
"")
        self.t1.setObjectName("t1")
        self.gridLayout.addWidget(self.t1, 0, 1, 1, 1)
        self.n8 = QtWidgets.QLineEdit(self.frame_3)
        self.n8.setMinimumSize(QtCore.QSize(0, 50))
        self.n8.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n8.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 19px \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.n8.setAlignment(QtCore.Qt.AlignCenter)
        self.n8.setObjectName("n8")
        self.gridLayout.addWidget(self.n8, 7, 3, 1, 1)
        self.t4 = QtWidgets.QToolButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t4.sizePolicy().hasHeightForWidth())
        self.t4.setSizePolicy(sizePolicy)
        self.t4.setMinimumSize(QtCore.QSize(0, 30))
        self.t4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.t4.setStyleSheet("color:white;\n"
"border-image: url(:/miccel/border_element.png);\n"
"border:none;\n"
"font: 14pt \"Orbitron\";")
        self.t4.setObjectName("t4")
        self.gridLayout.addWidget(self.t4, 3, 1, 1, 1)
        self.n3 = QtWidgets.QLineEdit(self.frame_3)
        self.n3.setMinimumSize(QtCore.QSize(0, 50))
        self.n3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n3.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 19px \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.n3.setAlignment(QtCore.Qt.AlignCenter)
        self.n3.setObjectName("n3")
        self.gridLayout.addWidget(self.n3, 2, 3, 1, 1)
        self.t3 = QtWidgets.QToolButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t3.sizePolicy().hasHeightForWidth())
        self.t3.setSizePolicy(sizePolicy)
        self.t3.setMinimumSize(QtCore.QSize(0, 30))
        self.t3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.t3.setStyleSheet("color:white;\n"
"border-image: url(:/miccel/border_element.png);\n"
"border:none;\n"
"font: 14pt \"Orbitron\";")
        self.t3.setObjectName("t3")
        self.gridLayout.addWidget(self.t3, 2, 1, 1, 1)
        self.n5 = QtWidgets.QLineEdit(self.frame_3)
        self.n5.setMinimumSize(QtCore.QSize(0, 50))
        self.n5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n5.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 19px \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.n5.setAlignment(QtCore.Qt.AlignCenter)
        self.n5.setObjectName("n5")
        self.gridLayout.addWidget(self.n5, 4, 3, 1, 1)
        self.f6 = QtWidgets.QLineEdit(self.frame_3)
        self.f6.setMinimumSize(QtCore.QSize(0, 55))
        self.f6.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f6.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 15px \"orbitron\";\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"border-image: url(:/miccel/border_element.png);")
        self.f6.setAlignment(QtCore.Qt.AlignCenter)
        self.f6.setObjectName("f6")
        self.gridLayout.addWidget(self.f6, 5, 0, 1, 1)
        self.t8 = QtWidgets.QToolButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t8.sizePolicy().hasHeightForWidth())
        self.t8.setSizePolicy(sizePolicy)
        self.t8.setMinimumSize(QtCore.QSize(0, 30))
        self.t8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.t8.setStyleSheet("color:white;\n"
"border-image: url(:/miccel/border_element.png);\n"
"border:none;\n"
"font: 14pt \"Orbitron\";")
        self.t8.setObjectName("t8")
        self.gridLayout.addWidget(self.t8, 7, 1, 1, 1)
        self.n2 = QtWidgets.QLineEdit(self.frame_3)
        self.n2.setMinimumSize(QtCore.QSize(0, 50))
        self.n2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n2.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 19px \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.n2.setAlignment(QtCore.Qt.AlignCenter)
        self.n2.setObjectName("n2")
        self.gridLayout.addWidget(self.n2, 1, 3, 1, 1)
        self.n4 = QtWidgets.QLineEdit(self.frame_3)
        self.n4.setMinimumSize(QtCore.QSize(0, 50))
        self.n4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n4.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 19px \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.n4.setAlignment(QtCore.Qt.AlignCenter)
        self.n4.setObjectName("n4")
        self.gridLayout.addWidget(self.n4, 3, 3, 1, 1)
        self.t5 = QtWidgets.QToolButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t5.sizePolicy().hasHeightForWidth())
        self.t5.setSizePolicy(sizePolicy)
        self.t5.setMinimumSize(QtCore.QSize(0, 30))
        self.t5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.t5.setStyleSheet("color:white;\n"
"border-image: url(:/miccel/border_element.png);\n"
"border:none;\n"
"font: 14pt \"Orbitron\";")
        self.t5.setObjectName("t5")
        self.gridLayout.addWidget(self.t5, 4, 1, 1, 1)
        self.f1 = QtWidgets.QLineEdit(self.frame_3)
        self.f1.setMinimumSize(QtCore.QSize(0, 55))
        self.f1.setMaximumSize(QtCore.QSize(401, 16777215))
        self.f1.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 15px \"orbitron\";\n"
"padding-left:20px;\n"
"padding-right:20px;\n"
"border-image: url(:/miccel/border_element.png);")
        self.f1.setAlignment(QtCore.Qt.AlignCenter)
        self.f1.setObjectName("f1")
        self.gridLayout.addWidget(self.f1, 0, 0, 1, 1)
        self.t6 = QtWidgets.QToolButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t6.sizePolicy().hasHeightForWidth())
        self.t6.setSizePolicy(sizePolicy)
        self.t6.setMinimumSize(QtCore.QSize(0, 30))
        self.t6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.t6.setStyleSheet("color:white;\n"
"border-image: url(:/miccel/border_element.png);\n"
"border:none;\n"
"font: 14pt \"Orbitron\";")
        self.t6.setObjectName("t6")
        self.gridLayout.addWidget(self.t6, 5, 1, 1, 1)
        self.n1 = QtWidgets.QLineEdit(self.frame_3)
        self.n1.setMinimumSize(QtCore.QSize(0, 50))
        self.n1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n1.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 19px \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.n1.setAlignment(QtCore.Qt.AlignCenter)
        self.n1.setObjectName("n1")
        self.gridLayout.addWidget(self.n1, 0, 3, 1, 1)
        self.n6 = QtWidgets.QLineEdit(self.frame_3)
        self.n6.setMinimumSize(QtCore.QSize(0, 50))
        self.n6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n6.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"padding-right:10px;\n"
"font: 19px \"Orbitron\";\n"
"border-image: url(:/miccel/border_element.png);\n"
"}")
        self.n6.setAlignment(QtCore.Qt.AlignCenter)
        self.n6.setObjectName("n6")
        self.gridLayout.addWidget(self.n6, 5, 3, 1, 1)
        self.f5 = QtWidgets.QLineEdit(self.frame_3)
        self.f5.setMinimumSize(QtCore.QSize(0, 55))
        self.f5.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f5.setStyleSheet("border-image: url(:/miccel/border_element.png);\n"
"color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 15px \"MS Shell Dlg 2\";")
        self.f5.setAlignment(QtCore.Qt.AlignCenter)
        self.f5.setObjectName("f5")
        self.gridLayout.addWidget(self.f5, 4, 0, 1, 1)
        self.t2 = QtWidgets.QToolButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t2.sizePolicy().hasHeightForWidth())
        self.t2.setSizePolicy(sizePolicy)
        self.t2.setMinimumSize(QtCore.QSize(0, 30))
        self.t2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.t2.setStyleSheet("color:white;\n"
"border-image: url(:/miccel/border_element.png);\n"
"border:none;\n"
"font: 14pt \"Orbitron\";")
        self.t2.setObjectName("t2")
        self.gridLayout.addWidget(self.t2, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 93))
        self.frame_4.setStyleSheet("border-image:none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setContentsMargins(39, 0, -1, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(26)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.instruction = QtWidgets.QLabel(self.frame_4)
        self.instruction.setStyleSheet("color:white;\n"
"font: 25 19px \"Orbitron\";")
        self.instruction.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.instruction.setObjectName("instruction")
        self.gridLayout_2.addWidget(self.instruction, 0, 0, 1, 1)
        self.back = QtWidgets.QPushButton(self.frame_4)
        self.back.setMinimumSize(QtCore.QSize(0, 77))
        self.back.setMaximumSize(QtCore.QSize(257, 16777215))
        self.back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.back.setAutoFillBackground(False)
        self.back.setStyleSheet("QPushButton{\n"
"background-image: url(:/buttons/close_button.png);\n"
"border:none;\n"
"background-repeat:no-repeat;\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid transparent;;\n"
"}")
        self.back.setText("")
        self.back.setObjectName("back")
        self.gridLayout_2.addWidget(self.back, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Programs"))
        self.label.setText(_translate("MainWindow", "Programs"))
        self.heading.setText(_translate("MainWindow", "File locations will be used to open programs by the AI"))
        self.t7.setText(_translate("MainWindow", "..."))
        self.t1.setText(_translate("MainWindow", "..."))
        self.t4.setText(_translate("MainWindow", "..."))
        self.t3.setText(_translate("MainWindow", "..."))
        self.t8.setText(_translate("MainWindow", "..."))
        self.t5.setText(_translate("MainWindow", "..."))
        self.f1.setPlaceholderText(_translate("MainWindow", "Program Path"))
        self.t6.setText(_translate("MainWindow", "..."))
        self.n1.setPlaceholderText(_translate("MainWindow", "Program name"))
        self.t2.setText(_translate("MainWindow", "..."))
        self.instruction.setText(_translate("MainWindow", "Say \"Open (Program Name)\""))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_file_location()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
