# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings_window-test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont,QFontDatabase


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 719)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:black;")
        QFontDatabase.addApplicationFont(':/Fonts/orbitron.light.ttf')
        QFontDatabase.addApplicationFont(':/Fonts/pdark.ttf')
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:transparent;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.Main_Frame = QtWidgets.QFrame(self.page)
        self.Main_Frame.setStyleSheet("border-image: url(:/Settings_window/Settings_background.png) 0 0 0 0 stretch stretch;\n"
"background-repeat:no-repeat;")
        self.Main_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_Frame.setObjectName("Main_Frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Main_Frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menu = QtWidgets.QFrame(self.Main_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setMinimumSize(QtCore.QSize(0, 75))
        self.menu.setStyleSheet("border-image:none;\n"
"background-color:transparent;")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menu)
        self.horizontalLayout.setContentsMargins(48, 1, 36, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_6 = QtWidgets.QFrame(self.menu)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.general_button = QtWidgets.QPushButton(self.frame_6)
        self.general_button.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"color: rgb(0, 255, 170);\n"
"\n"
"border:2px solid transparent;\n"
"border-bottom-color: rgb(0, 255, 170);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"}")
        self.general_button.setObjectName("general_button")
        self.gridLayout_2.addWidget(self.general_button, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_6)
        self.frame_4 = QtWidgets.QFrame(self.menu)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.personal_info_button = QtWidgets.QPushButton(self.frame_4)
        self.personal_info_button.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"color: white;\n"
"border:2px solid transparent;\n"
"border-bottom-color: White;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(0, 255, 170);\n"
"}")
        self.personal_info_button.setObjectName("personal_info_button")
        self.gridLayout_3.addWidget(self.personal_info_button, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.menu)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ai_info_button = QtWidgets.QPushButton(self.frame_5)
        self.ai_info_button.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"color: white;\n"
"\n"
"border:2px solid transparent;\n"
"border-bottom-color: White;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(0, 255, 170);\n"
"}")
        self.ai_info_button.setObjectName("ai_info_button")
        self.gridLayout_4.addWidget(self.ai_info_button, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(self.menu)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.history_button = QtWidgets.QPushButton(self.frame_7)
        self.history_button.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"color: white;\n"
"border:2px solid transparent;\n"
"border-bottom-color: White;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(0, 255, 170);\n"
"}")
        self.history_button.setObjectName("history_button")
        self.gridLayout_5.addWidget(self.history_button, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem3, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.menu, 0, QtCore.Qt.AlignTop)
        self.settings_part1 = QtWidgets.QFrame(self.Main_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_part1.sizePolicy().hasHeightForWidth())
        self.settings_part1.setSizePolicy(sizePolicy)
        self.settings_part1.setMaximumSize(QtCore.QSize(16777215, 200))
        self.settings_part1.setStyleSheet("border-image:none;\n"
"background-color:transparent;")
        self.settings_part1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings_part1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_part1.setObjectName("settings_part1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.settings_part1)
        self.gridLayout_6.setContentsMargins(65, 0, -1, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_12 = QtWidgets.QFrame(self.settings_part1)
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_12)
        self.checkBox_3.setStyleSheet("QCheckBox{\n"
"color:white;\n"
"font: 75 16px \"Orbitron\";\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    width: 20px;\n"
"    height: 15px;\n"
"background-color:rgb(0, 255, 170);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background:rectangle white;;\n"
"    height:15px;\n"
"    width:20px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    height:15px;\n"
"    width:20px;\n"
"    background-color:rgb(0, 255, 170);\n"
"}\n"
"")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_7.addWidget(self.checkBox_3, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_12, 1, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.settings_part1)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_10)
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkBox = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox.setStyleSheet("QCheckBox{\n"
"color:white;\n"
"font: 75 16px \"Orbitron\";\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 20px;\n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    width: 20px;\n"
"    height: 15px;\n"
"background-color:rgb(0, 255, 170);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background:rectangle white;;\n"
"    height:15px;\n"
"    width:20px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    height:15px;\n"
"    width:20px;\n"
"    background-color:rgb(0, 255, 170);\n"
"}\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_8.addWidget(self.checkBox, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_9)
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_11)
        self.checkBox_2.setStyleSheet("QCheckBox{\n"
"color:white;\n"
"font: 75 16px \"Orbitron\";\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    width: 20px;\n"
"    height: 15px;\n"
"background-color:rgb(0, 255, 170);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background:rectangle white;;\n"
"    height:15px;\n"
"    width:20px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    height:15px;\n"
"    width:20px;\n"
"    background-color:rgb(0, 255, 170);\n"
"}\n"
"")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_9.addWidget(self.checkBox_2, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_11)
        self.gridLayout_6.addWidget(self.frame_10, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem4, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.settings_part1)
        self.settings_part2 = QtWidgets.QFrame(self.Main_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_part2.sizePolicy().hasHeightForWidth())
        self.settings_part2.setSizePolicy(sizePolicy)
        self.settings_part2.setStyleSheet("border-image:none;\n"
"background-color:transparent;")
        self.settings_part2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings_part2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_part2.setObjectName("settings_part2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settings_part2)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_14 = QtWidgets.QFrame(self.settings_part2)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_3.setContentsMargins(21, 9, 0, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_17 = QtWidgets.QFrame(self.frame_14)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_4.setContentsMargins(28, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(17)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_17)
        self.label.setStyleSheet("font: 75 15px \"Orbitron\";\n"
"color:white;")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_3.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_14)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_5.setContentsMargins(14, 0, 29, 0)
        self.horizontalLayout_5.setSpacing(17)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.wakeup_hotkey = QtWidgets.QLineEdit(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wakeup_hotkey.sizePolicy().hasHeightForWidth())
        self.wakeup_hotkey.setSizePolicy(sizePolicy)
        self.wakeup_hotkey.setMinimumSize(QtCore.QSize(0, 20))
        self.wakeup_hotkey.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"border:none;\n"
"border:1px solid white;\n"
"    font: 25 11px \"Orbitron\";\n"
"padding-top:5px;\n"
"padding-bottom:5px;\n"
"padding-left:5px;\n"
"padding-right:15px;\n"
"    border-image: url(:/miccel/border_element.png);\n"
"padding:10px;\n"
"}\n"
"QLineEdit::hover{\n"
"border-color:rgba(255,255,255,50);\n"
"\n"
"}")
        self.wakeup_hotkey.setAlignment(QtCore.Qt.AlignCenter)
        self.wakeup_hotkey.setObjectName("wakeup_hotkey")
        self.horizontalLayout_5.addWidget(self.wakeup_hotkey)
        self.label_3 = QtWidgets.QLabel(self.frame_18)
        self.label_3.setStyleSheet("font: 75 15px \"Orbitron\";\n"
"color:white;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.sleep_hotkey = QtWidgets.QLineEdit(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sleep_hotkey.sizePolicy().hasHeightForWidth())
        self.sleep_hotkey.setSizePolicy(sizePolicy)
        self.sleep_hotkey.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"border:none;\n"
"border:1px solid white;\n"
"    font: 25 11px \"Orbitron\";\n"
"padding-top:5px;\n"
"padding-bottom:5px;\n"
"padding-left:5px;\n"
"padding-right:15px;\n"
"    border-image: url(:/miccel/border_element.png);\n"
"padding:10px;\n"
"}\n"
"QLineEdit::hover{\n"
"border-color:rgba(255,255,255,50);\n"
"\n"
"}")
        self.sleep_hotkey.setAlignment(QtCore.Qt.AlignCenter)
        self.sleep_hotkey.setObjectName("sleep_hotkey")
        self.horizontalLayout_5.addWidget(self.sleep_hotkey)
        self.horizontalLayout_3.addWidget(self.frame_18)
        self.verticalLayout_2.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.settings_part2)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_7.setContentsMargins(43, 0, 9, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_19 = QtWidgets.QFrame(self.frame_15)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_6.setContentsMargins(9, -1, 25, -1)
        self.horizontalLayout_6.setSpacing(19)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_19)
        self.label_2.setStyleSheet("color:white;\n"
"font: 25 16px \"Orbitron\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.combobox_microphone = QtWidgets.QComboBox(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_microphone.sizePolicy().hasHeightForWidth())
        self.combobox_microphone.setSizePolicy(sizePolicy)
        self.combobox_microphone.setMinimumSize(QtCore.QSize(132, 40))
        self.combobox_microphone.setStyleSheet("QComboBox{\n"
"border:none;\n"
"border:1px solid white;\n"
"color:white;\n"
"background-color:transparent;\n"
"padding-left:10px;\n"
"font: 25 11px \"Orbitron\";\n"
"    border-image: url(:/miccel/border_element.png);\n"
"padding:10px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"selection-background-color:  rgb(12, 230, 165);\n"
"outline:none;\n"
"selection-color:black;\n"
"}\n"
"QListView{\n"
"background-color:white;\n"
"color:black;\n"
"border:none;\n"
"}\n"
"")
        self.combobox_microphone.setObjectName("combobox_microphone")
        self.horizontalLayout_6.addWidget(self.combobox_microphone)
        self.horizontalLayout_7.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.frame_15)
        self.frame_20.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_8.setContentsMargins(0, -1, 39, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_20)
        self.label_4.setStyleSheet("color:white;\n"
"font: 25 16px \"Orbitron\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.combobox_audio = QtWidgets.QComboBox(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_audio.sizePolicy().hasHeightForWidth())
        self.combobox_audio.setSizePolicy(sizePolicy)
        self.combobox_audio.setMinimumSize(QtCore.QSize(152, 40))
        self.combobox_audio.setStyleSheet("QComboBox{\n"
"border:none;\n"
"border:1px solid white;\n"
"color:white;\n"
"background-color:transparent;\n"
"padding-left:10px;\n"
"    font: 25 11px \"Orbitron\";\n"
"    border-image: url(:/miccel/border_element.png);\n"
"padding:10px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"selection-background-color:  rgb(12, 230, 165);\n"
"outline:none;\n"
"selection-color:black;\n"
"}\n"
"QListView{\n"
"background-color:white;\n"
"color:black;\n"
"border:none;\n"
"}\n"
"")
        self.combobox_audio.setObjectName("combobox_audio")
        self.horizontalLayout_8.addWidget(self.combobox_audio)
        self.horizontalLayout_7.addWidget(self.frame_20)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.settings_part2)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_11.setContentsMargins(39, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_21 = QtWidgets.QFrame(self.frame_16)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.music_directory = QtWidgets.QLineEdit(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.music_directory.sizePolicy().hasHeightForWidth())
        self.music_directory.setSizePolicy(sizePolicy)
        self.music_directory.setMinimumSize(QtCore.QSize(0, 44))
        self.music_directory.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding-left:10px;\n"
"border:none;\n"
"border:1px solid white;\n"
"    font: 25 11px \"Orbitron\";\n"
"    border-image: url(:/miccel/border_element.png);\n"
"padding:10px;\n"
"}\n"
"QLineEdit::hover{\n"
"border-color:rgba(255,255,255,50);\n"
"\n"
"}")
        self.music_directory.setAlignment(QtCore.Qt.AlignCenter)
        self.music_directory.setObjectName("music_directory")
        self.horizontalLayout_9.addWidget(self.music_directory)
        self.toolButton = QtWidgets.QToolButton(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(0, 10))
        self.toolButton.setStyleSheet("QToolButton{\n"
"color:white;\n"
"border-image: url(:/miccel/border_element.png);\n"
"padding:8px;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"color: rgb(0, 217, 155);\n"
"}\n"
"\n"
"QToolButton::pressed{\n"
"color: rgb(0, 217, 155);\n"
"}")
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_9.addWidget(self.toolButton)
        self.horizontalLayout_11.addWidget(self.frame_21)
        self.frame_24 = QtWidgets.QFrame(self.frame_16)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_13.setContentsMargins(5, 18, 23, 0)
        self.horizontalLayout_13.setSpacing(7)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_6 = QtWidgets.QLabel(self.frame_24)
        self.label_6.setStyleSheet("color:white;\n"
"font: 15px \"Orbitron\";\n"
"padding-bottom:15px;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_13.addWidget(self.label_6)
        self.frame_65 = QtWidgets.QFrame(self.frame_24)
        self.frame_65.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_65.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_65.setObjectName("frame_65")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.frame_65)
        self.gridLayout_41.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_41.setSpacing(0)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.vooice_speed_control = QtWidgets.QSlider(self.frame_65)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vooice_speed_control.sizePolicy().hasHeightForWidth())
        self.vooice_speed_control.setSizePolicy(sizePolicy)
        self.vooice_speed_control.setMaximumSize(QtCore.QSize(200, 16777215))
        self.vooice_speed_control.setStyleSheet("QSlider::handle{\n"
"background-color: rgb(11, 236, 172);\n"
"}\n"
"QSlider::handle:hover{\n"
"background-color: rgba(0, 0, 0,80);\n"
"}")
        self.vooice_speed_control.setOrientation(QtCore.Qt.Horizontal)
        self.vooice_speed_control.setObjectName("vooice_speed_control")
        self.gridLayout_41.addWidget(self.vooice_speed_control, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_65)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_14.setStyleSheet("font: 25 11px \"Orbitron\";\n"
"color:white;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_41.addWidget(self.label_14, 2, 0, 1, 1)
        self.horizontalLayout_13.addWidget(self.frame_65)
        self.horizontalLayout_11.addWidget(self.frame_24)
        self.verticalLayout_2.addWidget(self.frame_16)
        self.frame_23 = QtWidgets.QFrame(self.settings_part2)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_23)
        self.gridLayout_12.setContentsMargins(41, -1, 24, -1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_25 = QtWidgets.QFrame(self.frame_23)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.power_permission = QtWidgets.QCheckBox(self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.power_permission.sizePolicy().hasHeightForWidth())
        self.power_permission.setSizePolicy(sizePolicy)
        self.power_permission.setStyleSheet("QCheckBox{\n"
"color:white;\n"
"font: 75 16px \"Orbitron\";\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    width: 20px;\n"
"    height: 15px;\n"
"background-color:rgb(0, 255, 170);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background:rectangle white;;\n"
"    height:15px;\n"
"    width:20px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    height:15px;\n"
"    width:20px;\n"
"    background-color:rgb(0, 255, 170);\n"
"}\n"
"")
        self.power_permission.setObjectName("power_permission")
        self.horizontalLayout_14.addWidget(self.power_permission)
        self.gridLayout_12.addWidget(self.frame_25, 0, 1, 1, 1)
        self.frame_26 = QtWidgets.QFrame(self.frame_23)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_26)
        self.gridLayout_14.setContentsMargins(32, -1, -1, -1)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.locked_at_launch = QtWidgets.QCheckBox(self.frame_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locked_at_launch.sizePolicy().hasHeightForWidth())
        self.locked_at_launch.setSizePolicy(sizePolicy)
        self.locked_at_launch.setStyleSheet("QCheckBox{\n"
"color:white;\n"
"font: 75 16px \"Orbitron\";\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background:rectangle white;;\n"
"    height:15px;\n"
"    width:20px;\n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    width: 20px;\n"
"    height: 15px;\n"
"background-color:rgb(0, 255, 170);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    height:15px;\n"
"    width:20px;\n"
"    background-color:rgb(0, 255, 170);\n"
"}\n"
"")
        self.locked_at_launch.setChecked(True)
        self.locked_at_launch.setObjectName("locked_at_launch")
        self.gridLayout_14.addWidget(self.locked_at_launch, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_26, 1, 0, 1, 1)
        self.frame_22 = QtWidgets.QFrame(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_22.sizePolicy().hasHeightForWidth())
        self.frame_22.setSizePolicy(sizePolicy)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_10.setSpacing(15)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.frame_22)
        self.label_5.setStyleSheet("color:white;\n"
"font: 15px \"Orbitron\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.volume_control = QtWidgets.QSlider(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volume_control.sizePolicy().hasHeightForWidth())
        self.volume_control.setSizePolicy(sizePolicy)
        self.volume_control.setStyleSheet("QSlider::handle{\n"
"background-color: rgb(11, 236, 172);\n"
"}\n"
"QSlider::handle:hover{\n"
"background-color: rgba(0, 0, 0,80);\n"
"}")
        self.volume_control.setOrientation(QtCore.Qt.Horizontal)
        self.volume_control.setObjectName("volume_control")
        self.horizontalLayout_10.addWidget(self.volume_control)
        self.gridLayout_12.addWidget(self.frame_22, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_23)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_13.setContentsMargins(-1, -1, 0, 38)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.back = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back.sizePolicy().hasHeightForWidth())
        self.back.setSizePolicy(sizePolicy)
        self.back.setMinimumSize(QtCore.QSize(0, 80))
        self.back.setMaximumSize(QtCore.QSize(200, 16777215))
        self.back.setStyleSheet("QPushButton{\n"
"    background-image: url(:/buttons/close_button.png);\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid transparent;;\n"
"}")
        self.back.setText("")
        self.back.setObjectName("back")
        self.gridLayout_13.addWidget(self.back, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem5, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_2, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_23)
        self.verticalLayout.addWidget(self.settings_part2)
        self.gridLayout_11.addWidget(self.Main_Frame, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.main_frame_2 = QtWidgets.QFrame(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_frame_2.sizePolicy().hasHeightForWidth())
        self.main_frame_2.setSizePolicy(sizePolicy)
        self.main_frame_2.setStyleSheet("border-image: url(:/Settings_window/personal_info_background.png);")
        self.main_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame_2.setObjectName("main_frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.main_frame_2)
        self.frame.setStyleSheet("border-image:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.menu_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_2.sizePolicy().hasHeightForWidth())
        self.menu_2.setSizePolicy(sizePolicy)
        self.menu_2.setMinimumSize(QtCore.QSize(0, 75))
        self.menu_2.setStyleSheet("border-image:none;\n"
"background-color:transparent;")
        self.menu_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_2.setObjectName("menu_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.menu_2)
        self.horizontalLayout_12.setContentsMargins(47, 0, 35, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_8 = QtWidgets.QFrame(self.menu_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.general_button_2 = QtWidgets.QPushButton(self.frame_8)
        self.general_button_2.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"color: white;\n"
"border:2px solid transparent;\n"
"border-bottom-color: white;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(1, 248, 165);\n"
"}")
        self.general_button_2.setObjectName("general_button_2")
        self.gridLayout_10.addWidget(self.general_button_2, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem6, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.frame_8)
        self.frame_13 = QtWidgets.QFrame(self.menu_2)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.personal_info_button_2 = QtWidgets.QPushButton(self.frame_13)
        self.personal_info_button_2.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"border:2px solid transparent;\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(0, 255, 170);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(0, 255, 170);\n"
"}")
        self.personal_info_button_2.setObjectName("personal_info_button_2")
        self.gridLayout_16.addWidget(self.personal_info_button_2, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_16.addItem(spacerItem7, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.frame_13)
        self.frame_27 = QtWidgets.QFrame(self.menu_2)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_27)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.ai_info_button_2 = QtWidgets.QPushButton(self.frame_27)
        self.ai_info_button_2.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"color: white;\n"
"border:2px solid transparent;\n"
"border-bottom-color: White;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(0, 255, 170);\n"
"}")
        self.ai_info_button_2.setObjectName("ai_info_button_2")
        self.gridLayout_17.addWidget(self.ai_info_button_2, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_17.addItem(spacerItem8, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.menu_2)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_28)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.history_button_2 = QtWidgets.QPushButton(self.frame_28)
        self.history_button_2.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"color: white;\n"
"border:2px solid transparent;\n"
"border-bottom-color: White;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(0, 255, 170);\n"
"}")
        self.history_button_2.setObjectName("history_button_2")
        self.gridLayout_18.addWidget(self.history_button_2, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_18.addItem(spacerItem9, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.frame_28)
        self.gridLayout_19.addWidget(self.menu_2, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.main_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("border-image:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_29 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_29.sizePolicy().hasHeightForWidth())
        self.frame_29.setSizePolicy(sizePolicy)
        self.frame_29.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_15.setContentsMargins(-1, 26, -1, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem10 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.label_7 = QtWidgets.QLabel(self.frame_29)
        self.label_7.setMaximumSize(QtCore.QSize(150, 200))
        self.label_7.setStyleSheet("border-image: url(:/miccel/personal_icon.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_15.addWidget(self.label_7)
        spacerItem11 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.verticalLayout_4.addWidget(self.frame_29, 0, QtCore.Qt.AlignTop)
        self.frame_30 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_30.sizePolicy().hasHeightForWidth())
        self.frame_30.setSizePolicy(sizePolicy)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_30)
        self.gridLayout_20.setContentsMargins(-1, -1, -1, 19)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.frame_31 = QtWidgets.QFrame(self.frame_30)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_16.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_34 = QtWidgets.QFrame(self.frame_31)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_8 = QtWidgets.QLabel(self.frame_34)
        self.label_8.setStyleSheet("color:white;\n"
"font: 25 16px \"Orbitron\";")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_17.addWidget(self.label_8)
        self.username_area = QtWidgets.QLineEdit(self.frame_34)
        self.username_area.setStyleSheet("QLineEdit{\n"
"border:1px solid transparent;\n"
"border-bottom-color:white;\n"
"border-radius:8px;\n"
"color:white;\n"
"padding-left:2px;\n"
"padding-right:2px;\n"
"    font: 25 12px \"Orbitron\";\n"
"    border-image: url(:/miccel/border_element.png);\n"
"padding:10px;\n"
"}\n"
"QLineEdit:hover{\n"
"border-bottom-color: rgb(1, 248, 165);\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color: rgb(1, 248, 165);\n"
"}")
        self.username_area.setObjectName("username_area")
        self.horizontalLayout_17.addWidget(self.username_area)
        self.horizontalLayout_16.addWidget(self.frame_34)
        self.frame_35 = QtWidgets.QFrame(self.frame_31)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_9 = QtWidgets.QLabel(self.frame_35)
        self.label_9.setStyleSheet("color:white;\n"
"font: 25 16px \"Orbitron\";")
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_18.addWidget(self.label_9)
        self.email_area = QtWidgets.QLineEdit(self.frame_35)
        self.email_area.setStyleSheet("QLineEdit{\n"
"border:1px solid transparent;\n"
"border-bottom-color:white;\n"
"border-radius:8px;\n"
"color:white;\n"
"padding-left:2px;\n"
"padding-right:2px;\n"
"    font: 25 12px \"Orbitron\";\n"
"    border-image: url(:/miccel/border_element.png);\n"
"padding:10px;\n"
"}\n"
"QLineEdit:hover{\n"
"border-bottom-color: rgb(1, 248, 165);\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom-color: rgb(1, 248, 165);\n"
"}")
        self.email_area.setObjectName("email_area")
        self.horizontalLayout_18.addWidget(self.email_area)
        self.horizontalLayout_16.addWidget(self.frame_35)
        self.gridLayout_20.addWidget(self.frame_31, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.frame_32 = QtWidgets.QFrame(self.frame_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_32.sizePolicy().hasHeightForWidth())
        self.frame_32.setSizePolicy(sizePolicy)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(17)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_36 = QtWidgets.QFrame(self.frame_32)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_10 = QtWidgets.QLabel(self.frame_36)
        self.label_10.setStyleSheet("color:white;\n"
"font: 25 16px \"Orbitron\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_20.addWidget(self.label_10)
        self.birth_date_area = QtWidgets.QDateEdit(self.frame_36)
        self.birth_date_area.setStyleSheet("QDateEdit\n"
"{\n"
"    background-color: transparent;\n"
"       border:1px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 15px \"Orbitron\";\n"
"    border-bottom-left-radius:10px;\n"
"padding-left:2px;\n"
"color:white;\n"
"    border-image: url(:/miccel/border_element.png);\n"
"padding:10px;\n"
"}\n"
"QDateEdit:hover{\n"
"border-bottom-color: rgb(1, 248, 165);;\n"
"color: rgb(1, 248, 165);\n"
"}\n"
"QDateEdit:focus{\n"
"border-bottom-color: rgb(1, 248, 165);;\n"
"color: rgb(1, 248, 165);\n"
"}\n"
"QDateEdit::up-button{\n"
"width:6px;\n"
"padding-right:25px;\n"
"}\n"
"QDateEdit::down-button{\n"
"width:6px;\n"
"padding-right:25px;\n"
"}")
        self.birth_date_area.setObjectName("birth_date_area")
        self.horizontalLayout_20.addWidget(self.birth_date_area)
        self.horizontalLayout_19.addWidget(self.frame_36)
        self.frame_37 = QtWidgets.QFrame(self.frame_32)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_21.setContentsMargins(0, 0, 57, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_11 = QtWidgets.QLabel(self.frame_37)
        self.label_11.setStyleSheet("color:white;\n"
"font: 25 16px \"Orbitron\";")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_21.addWidget(self.label_11)
        self.age_area = QtWidgets.QSpinBox(self.frame_37)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.age_area.sizePolicy().hasHeightForWidth())
        self.age_area.setSizePolicy(sizePolicy)
        self.age_area.setStyleSheet("QSpinBox{\n"
"    font: 25 15px \"Orbitron\";\n"
"border:none;\n"
"border:1px solid transparent;\n"
"border-bottom-color:white;\n"
"border-bottom-left-radius:10px;\n"
"padding-left:5px;\n"
"color:white;\n"
"    border-image: url(:/miccel/border_element.png);\n"
"padding:10px;\n"
"}\n"
"QSpinBox::up-button{\n"
"width:26px;\n"
"}\n"
"QSpinBox::down-button{\n"
"width:26px;\n"
"}\n"
"QSpinBox:hover{\n"
"border-bottom-color: rgb(1, 248, 165);\n"
"color: rgb(1, 248, 165);\n"
"}\n"
"QSpinBox:focus{\n"
"border-bottom-color: rgb(1, 248, 165);\n"
"color: rgb(1, 248, 165);\n"
"}")
        self.age_area.setObjectName("age_area")
        self.horizontalLayout_21.addWidget(self.age_area)
        self.horizontalLayout_19.addWidget(self.frame_37)
        self.gridLayout_20.addWidget(self.frame_32, 1, 1, 1, 1, QtCore.Qt.AlignTop)
        spacerItem12 = QtWidgets.QSpacerItem(36, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem12, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(36, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem13, 1, 0, 1, 1)
        self.frame_33 = QtWidgets.QFrame(self.frame_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_33.sizePolicy().hasHeightForWidth())
        self.frame_33.setSizePolicy(sizePolicy)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_40 = QtWidgets.QFrame(self.frame_33)
        self.frame_40.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.frame_38 = QtWidgets.QFrame(self.frame_40)
        self.frame_38.setStyleSheet("border:2px solid transparent;\n"
"border-right-color:white;")
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_38)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.male_radioButton = QtWidgets.QRadioButton(self.frame_38)
        self.male_radioButton.setStyleSheet("color:white;\n"
"font: 25 19px \"Orbitron\";\n"
"padding-left:30px;\n"
"border:none;")
        self.male_radioButton.setIconSize(QtCore.QSize(16, 16))
        self.male_radioButton.setObjectName("male_radioButton")
        self.horizontalLayout_23.addWidget(self.male_radioButton)
        self.female_radioButton = QtWidgets.QRadioButton(self.frame_38)
        self.female_radioButton.setStyleSheet("color:white;\n"
"font: 25 19px \"Orbitron\";\n"
"border:none;")
        self.female_radioButton.setObjectName("female_radioButton")
        self.horizontalLayout_23.addWidget(self.female_radioButton)
        self.horizontalLayout_22.addWidget(self.frame_38)
        self.frame_39 = QtWidgets.QFrame(self.frame_40)
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_39)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_12 = QtWidgets.QLabel(self.frame_39)
        self.label_12.setStyleSheet("color:white;\n"
"font: 25 16px \"Orbitron\";")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_21.addWidget(self.label_12, 0, 0, 1, 1)
        self.horizontalLayout_22.addWidget(self.frame_39)
        self.verticalLayout_5.addWidget(self.frame_40, 0, QtCore.Qt.AlignTop)
        self.frame_41 = QtWidgets.QFrame(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_41.sizePolicy().hasHeightForWidth())
        self.frame_41.setSizePolicy(sizePolicy)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_41)
        self.gridLayout_22.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_22.setSpacing(0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_13 = QtWidgets.QLabel(self.frame_41)
        self.label_13.setStyleSheet("color:white;\n"
"font: 25 16px \"Orbitron\";")
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_22.addWidget(self.label_13, 0, 0, 1, 1)
        self.frame_42 = QtWidgets.QFrame(self.frame_41)
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.frame_42)
        self.gridLayout_23.setContentsMargins(34, 4, 0, 35)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.back_2 = QtWidgets.QPushButton(self.frame_42)
        self.back_2.setMinimumSize(QtCore.QSize(0, 80))
        self.back_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.back_2.setStyleSheet("QPushButton{\n"
"    background-image: url(:/buttons/close_button.png);\n"
"background-repeat:none\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid transparent;;\n"
"}")
        self.back_2.setText("")
        self.back_2.setObjectName("back_2")
        self.gridLayout_23.addWidget(self.back_2, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(264, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem14, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.frame_42, 3, 0, 1, 1)
        self.note = QtWidgets.QLabel(self.frame_41)
        self.note.setStyleSheet("color:white;\n"
"font: 25 16px \"Orbitron\";")
        self.note.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.note.setObjectName("note")
        self.gridLayout_22.addWidget(self.note, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_41)
        self.gridLayout_20.addWidget(self.frame_33, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_30)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.gridLayout_15.addWidget(self.main_frame_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setSpacing(0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.frame_43 = QtWidgets.QFrame(self.page_3)
        self.frame_43.setStyleSheet("border-image: url(:/Settings_window/ai_info_background.png);")
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.frame_43)
        self.gridLayout_29.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_29.setSpacing(0)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.frame_48 = QtWidgets.QFrame(self.frame_43)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_48.sizePolicy().hasHeightForWidth())
        self.frame_48.setSizePolicy(sizePolicy)
        self.frame_48.setStyleSheet("border-image:none;")
        self.frame_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.frame_48)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.frame_49 = QtWidgets.QFrame(self.frame_48)
        self.frame_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setObjectName("frame_49")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.frame_49)
        self.gridLayout_31.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_31.setSpacing(0)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_15 = QtWidgets.QLabel(self.frame_49)
        self.label_15.setMinimumSize(QtCore.QSize(0, 0))
        self.label_15.setStyleSheet("border-image: url(:/miccel/Zera_image.png);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout_31.addWidget(self.label_15, 0, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem15, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.frame_49, 0, 0, 1, 1)
        self.frame_50 = QtWidgets.QFrame(self.frame_48)
        self.frame_50.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_50.setObjectName("frame_50")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_50)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_51 = QtWidgets.QFrame(self.frame_50)
        self.frame_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_51)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.frame_51)
        self.label_16.setStyleSheet("color:white;\n"
"font: 25 19px \"Orbitron\";")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.frame_54 = QtWidgets.QFrame(self.frame_51)
        self.frame_54.setStyleSheet("")
        self.frame_54.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_54.setObjectName("frame_54")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_54)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem16 = QtWidgets.QSpacerItem(37, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem16)
        self.label_17 = QtWidgets.QLabel(self.frame_54)
        self.label_17.setStyleSheet("color:white;\n"
"font: 19px \"Orbitron\";")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_25.addWidget(self.label_17)
        self.zera_radioButton = QtWidgets.QRadioButton(self.frame_54)
        self.zera_radioButton.setStyleSheet("color:white;\n"
"font: 19px \"Orbitron\";")
        self.zera_radioButton.setChecked(True)
        self.zera_radioButton.setObjectName("zera_radioButton")
        self.horizontalLayout_25.addWidget(self.zera_radioButton)
        self.jarvis_radioButton = QtWidgets.QRadioButton(self.frame_54)
        self.jarvis_radioButton.setStyleSheet("color:white;\n"
"font: 19px \"Orbitron\";")
        self.jarvis_radioButton.setObjectName("jarvis_radioButton")
        self.horizontalLayout_25.addWidget(self.jarvis_radioButton)
        spacerItem17 = QtWidgets.QSpacerItem(72, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem17)
        self.label_18 = QtWidgets.QLabel(self.frame_54)
        self.label_18.setStyleSheet("color:white;\n"
"font: 25 15px \"Orbitron\";\n"
"border:1px solid transparent;\n"
"border-left-color:white;")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_25.addWidget(self.label_18)
        self.verticalLayout_7.addWidget(self.frame_54)
        self.verticalLayout_6.addWidget(self.frame_51)
        self.frame_52 = QtWidgets.QFrame(self.frame_50)
        self.frame_52.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_52)
        self.horizontalLayout_26.setContentsMargins(0, 26, 0, 0)
        self.horizontalLayout_26.setSpacing(14)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.frame_55 = QtWidgets.QFrame(self.frame_52)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_55.sizePolicy().hasHeightForWidth())
        self.frame_55.setSizePolicy(sizePolicy)
        self.frame_55.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_55.setObjectName("frame_55")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_55)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem18 = QtWidgets.QSpacerItem(72, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem18)
        self.label_19 = QtWidgets.QLabel(self.frame_55)
        self.label_19.setStyleSheet("color:white;\n"
"font: 19px \"orbitron\";")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_27.addWidget(self.label_19)
        self.voice_selector_comboBox = QtWidgets.QComboBox(self.frame_55)
        self.voice_selector_comboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.voice_selector_comboBox.setStyleSheet("QComboBox{\n"
"border:none;\n"
"border:1px solid transparent;\n"
"border-bottom-color:white;\n"
"color:white;\n"
"background-color:transparent;\n"
"padding-left:10px;\n"
"    font: 25 15px \"Orbitron\";\n"
"    border-image: url(:/miccel/border_element.png);\n"
"padding:10px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"selection-background-color:  rgb(12, 230, 165);\n"
"outline:none;\n"
"selection-color:black;\n"
"}\n"
"QListView{\n"
"background-color:white;\n"
"color:black;\n"
"border:none;\n"
"}\n"
"\n"
"")
        self.voice_selector_comboBox.setObjectName("voice_selector_comboBox")
        self.horizontalLayout_27.addWidget(self.voice_selector_comboBox)
        self.horizontalLayout_26.addWidget(self.frame_55)
        self.label_20 = QtWidgets.QLabel(self.frame_52)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_20.setStyleSheet("color:white;\n"
"font: 25 15px \"Orbitron\";\n"
"border:1px solid transparent;\n"
"border-left-color:white;")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_26.addWidget(self.label_20, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addWidget(self.frame_52)
        self.frame_53 = QtWidgets.QFrame(self.frame_50)
        self.frame_53.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.frame_53)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setSpacing(0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        spacerItem19 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem19, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_53)
        self.label_21.setStyleSheet("color:white;\n"
"font: 25 19px \"Orbitron\";")
        self.label_21.setObjectName("label_21")
        self.gridLayout_32.addWidget(self.label_21, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        spacerItem20 = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_32.addItem(spacerItem20, 1, 2, 1, 1)
        self.back_3 = QtWidgets.QPushButton(self.frame_53)
        self.back_3.setMinimumSize(QtCore.QSize(0, 80))
        self.back_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.back_3.setStyleSheet("QPushButton{\n"
"    background-image: url(:/buttons/close_button.png);\n"
"background-repeat:none\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid transparent;;\n"
"}")
        self.back_3.setText("")
        self.back_3.setObjectName("back_3")
        self.gridLayout_32.addWidget(self.back_3, 0, 2, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem21, 0, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_53)
        self.gridLayout_30.addWidget(self.frame_50, 1, 0, 1, 1)
        self.gridLayout_29.addWidget(self.frame_48, 1, 0, 1, 1)
        self.menu_3 = QtWidgets.QFrame(self.frame_43)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_3.sizePolicy().hasHeightForWidth())
        self.menu_3.setSizePolicy(sizePolicy)
        self.menu_3.setMinimumSize(QtCore.QSize(0, 75))
        self.menu_3.setStyleSheet("border-image:none;\n"
"background-color:transparent;")
        self.menu_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_3.setObjectName("menu_3")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.menu_3)
        self.horizontalLayout_24.setContentsMargins(48, 1, 36, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.frame_44 = QtWidgets.QFrame(self.menu_3)
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.frame_44)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.general_button_3 = QtWidgets.QPushButton(self.frame_44)
        self.general_button_3.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"color: white;\n"
"border:2px solid transparent;\n"
"border-bottom-color: white;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(1, 248, 165);\n"
"}")
        self.general_button_3.setObjectName("general_button_3")
        self.gridLayout_25.addWidget(self.general_button_3, 1, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_25.addItem(spacerItem22, 0, 0, 1, 1)
        self.horizontalLayout_24.addWidget(self.frame_44)
        self.frame_45 = QtWidgets.QFrame(self.menu_3)
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.frame_45)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.personal_info_button_3 = QtWidgets.QPushButton(self.frame_45)
        self.personal_info_button_3.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"color: white;\n"
"border:2px solid transparent;\n"
"border-bottom-color: white;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(1, 248, 165);\n"
"}")
        self.personal_info_button_3.setObjectName("personal_info_button_3")
        self.gridLayout_26.addWidget(self.personal_info_button_3, 1, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_26.addItem(spacerItem23, 0, 0, 1, 1)
        self.horizontalLayout_24.addWidget(self.frame_45)
        self.frame_46 = QtWidgets.QFrame(self.menu_3)
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.frame_46)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.ai_info_button_3 = QtWidgets.QPushButton(self.frame_46)
        self.ai_info_button_3.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"border:2px solid transparent;\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(0, 255, 170);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(0, 255, 170);\n"
"}")
        self.ai_info_button_3.setObjectName("ai_info_button_3")
        self.gridLayout_27.addWidget(self.ai_info_button_3, 1, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_27.addItem(spacerItem24, 0, 0, 1, 1)
        self.horizontalLayout_24.addWidget(self.frame_46)
        self.frame_47 = QtWidgets.QFrame(self.menu_3)
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.frame_47)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.history_button_3 = QtWidgets.QPushButton(self.frame_47)
        self.history_button_3.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"color: white;\n"
"border:2px solid transparent;\n"
"border-bottom-color: White;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(0, 255, 170);\n"
"}")
        self.history_button_3.setObjectName("history_button_3")
        self.gridLayout_28.addWidget(self.history_button_3, 1, 0, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_28.addItem(spacerItem25, 0, 0, 1, 1)
        self.horizontalLayout_24.addWidget(self.frame_47)
        self.gridLayout_29.addWidget(self.menu_3, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout_24.addWidget(self.frame_43, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_33.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_33.setSpacing(0)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.frame_56 = QtWidgets.QFrame(self.page_4)
        self.frame_56.setStyleSheet("border-image: url(:/Settings_window/history_background.png);")
        self.frame_56.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_56.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_56.setObjectName("frame_56")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_56)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.menu_4 = QtWidgets.QFrame(self.frame_56)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_4.sizePolicy().hasHeightForWidth())
        self.menu_4.setSizePolicy(sizePolicy)
        self.menu_4.setMinimumSize(QtCore.QSize(0, 75))
        self.menu_4.setStyleSheet("border-image:none;\n"
"background-color:transparent;")
        self.menu_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_4.setObjectName("menu_4")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.menu_4)
        self.horizontalLayout_28.setContentsMargins(48, 1, 36, 0)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.frame_57 = QtWidgets.QFrame(self.menu_4)
        self.frame_57.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_57.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_57.setObjectName("frame_57")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.frame_57)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.general_button_4 = QtWidgets.QPushButton(self.frame_57)
        self.general_button_4.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"color: white;\n"
"border:2px solid transparent;\n"
"border-bottom-color: white;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(1, 248, 165);\n"
"}")
        self.general_button_4.setObjectName("general_button_4")
        self.gridLayout_34.addWidget(self.general_button_4, 1, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_34.addItem(spacerItem26, 0, 0, 1, 1)
        self.horizontalLayout_28.addWidget(self.frame_57)
        self.frame_58 = QtWidgets.QFrame(self.menu_4)
        self.frame_58.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_58.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_58.setObjectName("frame_58")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.frame_58)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.personal_info_button_4 = QtWidgets.QPushButton(self.frame_58)
        self.personal_info_button_4.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"color: white;\n"
"border:2px solid transparent;\n"
"border-bottom-color: white;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(1, 248, 165);\n"
"}")
        self.personal_info_button_4.setObjectName("personal_info_button_4")
        self.gridLayout_35.addWidget(self.personal_info_button_4, 1, 0, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_35.addItem(spacerItem27, 0, 0, 1, 1)
        self.horizontalLayout_28.addWidget(self.frame_58)
        self.frame_59 = QtWidgets.QFrame(self.menu_4)
        self.frame_59.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_59.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_59.setObjectName("frame_59")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.frame_59)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.ai_info_button_4 = QtWidgets.QPushButton(self.frame_59)
        self.ai_info_button_4.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"color: white;\n"
"border:2px solid transparent;\n"
"border-bottom-color: white;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(1, 248, 165);\n"
"}")
        self.ai_info_button_4.setObjectName("ai_info_button_4")
        self.gridLayout_36.addWidget(self.ai_info_button_4, 1, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_36.addItem(spacerItem28, 0, 0, 1, 1)
        self.horizontalLayout_28.addWidget(self.frame_59)
        self.frame_60 = QtWidgets.QFrame(self.menu_4)
        self.frame_60.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_60.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_60.setObjectName("frame_60")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.frame_60)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.history_button_4 = QtWidgets.QPushButton(self.frame_60)
        self.history_button_4.setStyleSheet("QPushButton{\n"
"font: 75 17px \"Orbitron\";\n"
"border:2px solid transparent;\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(0, 255, 170);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 255, 170);\n"
"border-bottom-color: rgb(0, 255, 170);\n"
"}")
        self.history_button_4.setObjectName("history_button_4")
        self.gridLayout_37.addWidget(self.history_button_4, 1, 0, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_37.addItem(spacerItem29, 0, 0, 1, 1)
        self.horizontalLayout_28.addWidget(self.frame_60)
        self.verticalLayout_8.addWidget(self.menu_4, 0, QtCore.Qt.AlignTop)
        self.frame_61 = QtWidgets.QFrame(self.frame_56)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_61.sizePolicy().hasHeightForWidth())
        self.frame_61.setSizePolicy(sizePolicy)
        self.frame_61.setStyleSheet("border-image:none;")
        self.frame_61.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.frame_61)
        self.gridLayout_38.setObjectName("gridLayout_38")
        spacerItem30 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_38.addItem(spacerItem30, 0, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.frame_61)
        self.textEdit.setStyleSheet("QTextEdit{\n"
"color:white;\n"
"    font: 25 19px \"Orbitron\";\n"
"padding-left:10px;\n"
"border:none;\n"
"border:2px solid transparent;\n"
"\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #999999;\n"
"    background:white;\n"
"    width:10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    \n"
"    background-color: rgb(3, 199, 143);\n"
"    min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0 rgb(32, 47, 130), stop: 0.5 rgb(32, 47, 130),  stop:1 rgb(32, 47, 130));\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop: 0  rgb(32, 47, 130), stop: 0.5 rgb(32, 47, 130),  stop:1 rgb(32, 47, 130));\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_38.addWidget(self.textEdit, 3, 1, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(41, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_38.addItem(spacerItem31, 3, 0, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(20, 42, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_38.addItem(spacerItem32, 5, 1, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_38.addItem(spacerItem33, 3, 2, 1, 1)
        self.frame_62 = QtWidgets.QFrame(self.frame_61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_62.sizePolicy().hasHeightForWidth())
        self.frame_62.setSizePolicy(sizePolicy)
        self.frame_62.setMaximumSize(QtCore.QSize(16777215, 90))
        self.frame_62.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_62.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_62.setObjectName("frame_62")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_62)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.frame_63 = QtWidgets.QFrame(self.frame_62)
        self.frame_63.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_63.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_63.setObjectName("frame_63")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.frame_63)
        self.gridLayout_40.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_40.setSpacing(0)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.clear_button = QtWidgets.QPushButton(self.frame_63)
        self.clear_button.setStyleSheet("QPushButton{\n"
"color:white;\n"
"    font: 25 32px \"Orbitron\";\n"
"}\n"
"QPushButton::hover{\n"
"    color: rgb(2, 205, 147);\n"
"\n"
"}")
        self.clear_button.setObjectName("clear_button")
        self.gridLayout_40.addWidget(self.clear_button, 0, 1, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_40.addItem(spacerItem34, 0, 0, 1, 1)
        self.horizontalLayout_29.addWidget(self.frame_63)
        self.frame_64 = QtWidgets.QFrame(self.frame_62)
        self.frame_64.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_64.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_64.setObjectName("frame_64")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.frame_64)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.back_4 = QtWidgets.QPushButton(self.frame_64)
        self.back_4.setMinimumSize(QtCore.QSize(0, 80))
        self.back_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.back_4.setStyleSheet("QPushButton{\n"
"    background-image: url(:/buttons/close_button.png);\n"
"background-repeat:none\n"
"}\n"
"QPushButton::hover{\n"
"border:2px solid transparent;;\n"
"}")
        self.back_4.setText("")
        self.back_4.setObjectName("back_4")
        self.gridLayout_39.addWidget(self.back_4, 0, 1, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_39.addItem(spacerItem35, 0, 0, 1, 1)
        self.horizontalLayout_29.addWidget(self.frame_64)
        self.gridLayout_38.addWidget(self.frame_62, 4, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_61)
        self.label_22.setStyleSheet("font: 25 35px \"Orbitron\";\n"
"color:white;;")
        self.label_22.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_38.addWidget(self.label_22, 1, 1, 2, 1)
        self.verticalLayout_8.addWidget(self.frame_61)
        self.gridLayout_33.addWidget(self.frame_56, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Settings"))
        self.general_button.setText(_translate("MainWindow", "General"))
        self.personal_info_button.setText(_translate("MainWindow", "Info"))
        self.ai_info_button.setText(_translate("MainWindow", "Ai info"))
        self.history_button.setText(_translate("MainWindow", "History"))
        self.checkBox_3.setText(_translate("MainWindow", "  Show confirmation dialog box whille exiting"))
        self.checkBox.setText(_translate("MainWindow", "Wakeup Greetings"))
        self.checkBox_2.setText(_translate("MainWindow", "Sleep Greetings"))
        self.label.setText(_translate("MainWindow", "Wakeup Hotkey"))
        self.wakeup_hotkey.setText(_translate("MainWindow", "Tab"))
        self.label_3.setText(_translate("MainWindow", "Sleep Hotkey"))
        self.sleep_hotkey.setText(_translate("MainWindow", "Home"))
        self.label_2.setText(_translate("MainWindow", "Microphone"))
        self.label_4.setText(_translate("MainWindow", "Audio"))
        self.music_directory.setPlaceholderText(_translate("MainWindow", "Music Directory"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label_6.setText(_translate("MainWindow", "Voice Speed"))
        self.label_14.setText(_translate("MainWindow", "300"))
        self.power_permission.setText(_translate("MainWindow", "Allow Shutdown / Restart"))
        self.locked_at_launch.setText(_translate("MainWindow", "Set Locked at launch"))
        self.label_5.setText(_translate("MainWindow", "Volume"))
        self.general_button_2.setText(_translate("MainWindow", "General"))
        self.personal_info_button_2.setText(_translate("MainWindow", "Info"))
        self.ai_info_button_2.setText(_translate("MainWindow", "Ai info"))
        self.history_button_2.setText(_translate("MainWindow", "History"))
        self.label_8.setText(_translate("MainWindow", "Username-"))
        self.label_9.setText(_translate("MainWindow", "Email Address-"))
        self.label_10.setText(_translate("MainWindow", "Date Of Birth-"))
        self.label_11.setText(_translate("MainWindow", "Age-"))
        self.male_radioButton.setText(_translate("MainWindow", "Male"))
        self.female_radioButton.setText(_translate("MainWindow", "Female"))
        self.label_12.setText(_translate("MainWindow", "Male- Sir,  Female-Maam"))
        self.label_13.setText(_translate("MainWindow", "Note- The data saved here will remain inside the software"))
        self.note.setText(_translate("MainWindow", "only and not be shared with anybody "))
        self.label_16.setText(_translate("MainWindow", "Current AI :- ZERA"))
        self.label_17.setText(_translate("MainWindow", "AI:-"))
        self.zera_radioButton.setText(_translate("MainWindow", "ZERA"))
        self.jarvis_radioButton.setText(_translate("MainWindow", "Jarvis"))
        self.label_18.setText(_translate("MainWindow", "Restart Required"))
        self.label_19.setText(_translate("MainWindow", "Available voices:-"))
        self.label_20.setText(_translate("MainWindow", "Restart Required"))
        self.label_21.setText(_translate("MainWindow", "Version- 4.0.0.0"))
        self.general_button_3.setText(_translate("MainWindow", "General"))
        self.personal_info_button_3.setText(_translate("MainWindow", "Info"))
        self.ai_info_button_3.setText(_translate("MainWindow", "Ai info"))
        self.history_button_3.setText(_translate("MainWindow", "History"))
        self.general_button_4.setText(_translate("MainWindow", "General"))
        self.personal_info_button_4.setText(_translate("MainWindow", "Info"))
        self.ai_info_button_4.setText(_translate("MainWindow", "Ai info"))
        self.history_button_4.setText(_translate("MainWindow", "History"))
        self.clear_button.setText(_translate("MainWindow", "CLEAR"))
        self.label_22.setText(_translate("MainWindow", "HISTORY"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
