# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Loading_responsive.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import ctypes,shutil
# hiding the window
ctypes.windll.user32.ShowWindow( ctypes.windll.kernel32.GetConsoleWindow(), 0 )

# try:
#         shutil.rmtree('C:\\ProgramData\\ZeraAI')
# except:
#         pass

from PyQt5 import QtCore, QtGui, QtWidgets
import time
from PyQt5.QtCore import QTimer
from PyQt5.QtGui import QFont,QFontDatabase
import sys

class Ui_loading_win(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 389)
        MainWindow.setWindowOpacity(0.987678)
        MainWindow.setStyleSheet("background-color: rgb(10, 10, 31);")
        MainWindow.setWindowFlags(QtCore.Qt.Widget | QtCore.Qt.FramelessWindowHint)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bgImage/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        QFontDatabase.addApplicationFont(':/bgImage/Azonix-1VB0.otf')
        QFontDatabase.addApplicationFont(':/bgImage/pdark.ttf')
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(-1, 20, -1, 64)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("color: rgb(85, 85, 255);\n"
"font: 50pt \"MS Shell Dlg2\";\n"
"background-color:transparent;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"background-color:transparent;\n"
"color: rgb(88, 88, 206);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color:transparent;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LoadingBAr = QtWidgets.QProgressBar(self.frame_2)
        self.LoadingBAr.setMinimumSize(QtCore.QSize(0, 45))
        self.LoadingBAr.setStyleSheet("QProgressBar{\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color:white;\n"
"text-align:center;\n"
"border:3px solid cyan;\n"
"border-radius:20px;\n"
"border-color:cyan;\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"background-color:cyan;\n"
"border:2px solid  rgb(10, 10, 31);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.LoadingBAr.setProperty("value", 24)
        self.LoadingBAr.setObjectName("LoadingBAr")
        self.horizontalLayout.addWidget(self.LoadingBAr)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("background-color:transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(101, 101, 206);\n"
"background-color:transparent;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setStyleSheet("background-color:transparent;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(101, 101, 206);\n"
"background-color:transparent;\n"
"background-color:transparent;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.verticalLayout.addWidget(self.frame_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZERA - The Advanced AI"))
        self.label_2.setText(_translate("MainWindow", " Welcome To <strong>ZERA AI "))
        self.label_3.setText(_translate("MainWindow", "  By Yash Akarsh"))
        self.label_4.setText(_translate("MainWindow", "Follow me on :-"))
        self.label_5.setText(_translate("MainWindow", "Youtube:- Tech Relatives"))
        
        # checker
        import os
        

import res_rc

if __name__ == "__main__":
        import os
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_loading_win()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
