# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings-file_location.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont,QFontDatabase

class Ui_file_location(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 651)
        # MainWindow.setMinimumSize(QtCore.QSize(400, 0))
        # MainWindow.setMaximumSize(QtCore.QSize(100000, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bgImage/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.97)
        MainWindow.setStyleSheet("background-color:black;")
        QFontDatabase.addApplicationFont(':/bgImage/Azonix-1VB0.otf')
        QFontDatabase.addApplicationFont(':/bgImage/pdark.ttf')
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.general = QtWidgets.QPushButton(self.frame_2)
        self.general.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.general.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 14pt \"Azonix\";\n"
"    color:white;\n"
"padding:10px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.general.setObjectName("general")
        self.horizontalLayout.addWidget(self.general, 0, QtCore.Qt.AlignTop)
        self.personal_info = QtWidgets.QPushButton(self.frame_2)
        self.personal_info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.personal_info.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 14pt \"Azonix\";\n"
"    color:white;\n"
"padding:10px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}\n"
"")
        self.personal_info.setObjectName("personal_info")
        self.horizontalLayout.addWidget(self.personal_info, 0, QtCore.Qt.AlignTop)
        self.Ai_info = QtWidgets.QPushButton(self.frame_2)
        self.Ai_info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Ai_info.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 14pt \"Azonix\";\n"
"    color:white;\n"
"padding:10px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.Ai_info.setObjectName("Ai_info")
        self.horizontalLayout.addWidget(self.Ai_info, 0, QtCore.Qt.AlignTop)
        self.Premium = QtWidgets.QPushButton(self.frame_2)
        self.Premium.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Premium.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 14pt \"Azonix\";\n"
"    color:white;\n"
"padding:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.Premium.setObjectName("Premium")
        self.horizontalLayout.addWidget(self.Premium, 0, QtCore.Qt.AlignTop)
        self.programs = QtWidgets.QPushButton(self.frame_2)
        self.programs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.programs.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 14pt \"Azonix\";\n"
"    color:white;\n"
"padding:10px;\n"
"color:rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.programs.setObjectName("programs")
        self.horizontalLayout.addWidget(self.programs, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.heading = QtWidgets.QLabel(self.frame)
        self.heading.setStyleSheet("font: 18pt \"Azonix\";\n"
"color:white;\n"
"background-color:transparent;")
        self.heading.setAlignment(QtCore.Qt.AlignCenter)
        self.heading.setObjectName("heading")
        self.horizontalLayout_2.addWidget(self.heading)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.f3 = QtWidgets.QLineEdit(self.frame_3)
        self.f3.setMinimumSize(QtCore.QSize(0, 40))
        self.f3.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f3.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.f3.setObjectName("f3")
        self.gridLayout.addWidget(self.f3, 2, 0, 1, 1)
        self.f1 = QtWidgets.QLineEdit(self.frame_3)
        self.f1.setMinimumSize(QtCore.QSize(0, 40))
        self.f1.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f1.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n;")
        self.f1.setObjectName("f1")
        self.gridLayout.addWidget(self.f1, 0, 0, 1, 1)
        self.n2 = QtWidgets.QLineEdit(self.frame_3)
        self.n2.setMinimumSize(QtCore.QSize(0, 50))
        self.n2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n2.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding:5px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"border-radius:10px;\n"
"}")
        self.n2.setAlignment(QtCore.Qt.AlignCenter)
        self.n2.setObjectName("n2")
        self.gridLayout.addWidget(self.n2, 1, 3, 1, 1)
        self.t5 = QtWidgets.QToolButton(self.frame_3)
        self.t5.setMinimumSize(QtCore.QSize(0, 30))
        self.t5.setStyleSheet("background-color:white;\n"
"border:none;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.t5.setObjectName("t5")
        self.gridLayout.addWidget(self.t5, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 3, 1, 1)
        self.f5 = QtWidgets.QLineEdit(self.frame_3)
        self.f5.setMinimumSize(QtCore.QSize(0, 40))
        self.f5.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f5.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.f5.setObjectName("f5")
        self.gridLayout.addWidget(self.f5, 4, 0, 1, 1)
        self.t4 = QtWidgets.QToolButton(self.frame_3)
        self.t4.setMinimumSize(QtCore.QSize(0, 30))
        self.t4.setStyleSheet("background-color:white;\n"
"border:none;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.t4.setObjectName("t4")
        self.gridLayout.addWidget(self.t4, 3, 1, 1, 1)
        self.n5 = QtWidgets.QLineEdit(self.frame_3)
        self.n5.setMinimumSize(QtCore.QSize(0, 50))
        self.n5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n5.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding:5px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"border-radius:10px;\n"
"}")
        self.n5.setAlignment(QtCore.Qt.AlignCenter)
        self.n5.setObjectName("n5")
        self.gridLayout.addWidget(self.n5, 4, 3, 1, 1)
        self.t7 = QtWidgets.QToolButton(self.frame_3)
        self.t7.setMinimumSize(QtCore.QSize(0, 30))
        self.t7.setStyleSheet("background-color:white;\n"
"border:none;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.t7.setObjectName("t7")
        self.gridLayout.addWidget(self.t7, 6, 1, 1, 1)
        self.n4 = QtWidgets.QLineEdit(self.frame_3)
        self.n4.setMinimumSize(QtCore.QSize(0, 50))
        self.n4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n4.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding:5px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"border-radius:10px;\n"
"}")
        self.n4.setAlignment(QtCore.Qt.AlignCenter)
        self.n4.setObjectName("n4")
        self.gridLayout.addWidget(self.n4, 3, 3, 1, 1)
        self.t3 = QtWidgets.QToolButton(self.frame_3)
        self.t3.setMinimumSize(QtCore.QSize(0, 30))
        self.t3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.t3.setStyleSheet("background-color:white;\n"
"border:none;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.t3.setObjectName("t3")
        self.gridLayout.addWidget(self.t3, 2, 1, 1, 1)
        self.n6 = QtWidgets.QLineEdit(self.frame_3)
        self.n6.setMinimumSize(QtCore.QSize(0, 50))
        self.n6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n6.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding:5px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"border-radius:10px;\n"
"}")
        self.n6.setAlignment(QtCore.Qt.AlignCenter)
        self.n6.setObjectName("n6")
        self.gridLayout.addWidget(self.n6, 5, 3, 1, 1)
        self.n1 = QtWidgets.QLineEdit(self.frame_3)
        self.n1.setMinimumSize(QtCore.QSize(0, 50))
        self.n1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n1.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding:5px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"border-radius:10px;\n"
"}")
        self.n1.setAlignment(QtCore.Qt.AlignCenter)
        self.n1.setObjectName("n1")
        self.gridLayout.addWidget(self.n1, 0, 3, 1, 1)
        self.t2 = QtWidgets.QToolButton(self.frame_3)
        self.t2.setMinimumSize(QtCore.QSize(0, 30))
        self.t2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.t2.setStyleSheet("background-color:white;\n"
"border:none;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.t2.setObjectName("t2")
        self.gridLayout.addWidget(self.t2, 1, 1, 1, 1)
        self.f2 = QtWidgets.QLineEdit(self.frame_3)
        self.f2.setMinimumSize(QtCore.QSize(0, 40))
        self.f2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f2.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.f2.setObjectName("f2")
        self.gridLayout.addWidget(self.f2, 1, 0, 1, 1)
        self.n8 = QtWidgets.QLineEdit(self.frame_3)
        self.n8.setMinimumSize(QtCore.QSize(0, 50))
        self.n8.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n8.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding:5px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"border-radius:10px;\n"
"}")
        self.n8.setAlignment(QtCore.Qt.AlignCenter)
        self.n8.setObjectName("n8")
        self.gridLayout.addWidget(self.n8, 7, 3, 1, 1)
        self.f4 = QtWidgets.QLineEdit(self.frame_3)
        self.f4.setMinimumSize(QtCore.QSize(0, 40))
        self.f4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f4.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.f4.setObjectName("f4")
        self.gridLayout.addWidget(self.f4, 3, 0, 1, 1)
        self.f6 = QtWidgets.QLineEdit(self.frame_3)
        self.f6.setMinimumSize(QtCore.QSize(0, 40))
        self.f6.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f6.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.f6.setObjectName("f6")
        self.gridLayout.addWidget(self.f6, 5, 0, 1, 1)
        self.t6 = QtWidgets.QToolButton(self.frame_3)
        self.t6.setMinimumSize(QtCore.QSize(0, 30))
        self.t6.setStyleSheet("background-color:white;\n"
"border:none;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.t6.setObjectName("t6")
        self.gridLayout.addWidget(self.t6, 5, 1, 1, 1)
        self.f8 = QtWidgets.QLineEdit(self.frame_3)
        self.f8.setMinimumSize(QtCore.QSize(0, 40))
        self.f8.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f8.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.f8.setObjectName("f8")
        self.gridLayout.addWidget(self.f8, 7, 0, 1, 1)
        self.n7 = QtWidgets.QLineEdit(self.frame_3)
        self.n7.setMinimumSize(QtCore.QSize(0, 50))
        self.n7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n7.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding:5px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"border-radius:10px;\n"
"}")
        self.n7.setAlignment(QtCore.Qt.AlignCenter)
        self.n7.setObjectName("n7")
        self.gridLayout.addWidget(self.n7, 6, 3, 1, 1)
        self.f7 = QtWidgets.QLineEdit(self.frame_3)
        self.f7.setMinimumSize(QtCore.QSize(0, 40))
        self.f7.setMaximumSize(QtCore.QSize(400, 16777215))
        self.f7.setStyleSheet("color:white;\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.f7.setObjectName("f7")
        self.gridLayout.addWidget(self.f7, 6, 0, 1, 1)
        self.n3 = QtWidgets.QLineEdit(self.frame_3)
        self.n3.setMinimumSize(QtCore.QSize(0, 50))
        self.n3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.n3.setStyleSheet("QLineEdit{\n"
"color:white;\n"
"padding:5px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border:2px solid;\n"
"border-color: rgb(0, 155, 233);\n"
"border-top-left-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"border-radius:10px;\n"
"}")
        self.n3.setAlignment(QtCore.Qt.AlignCenter)
        self.n3.setObjectName("n3")
        self.gridLayout.addWidget(self.n3, 2, 3, 1, 1)
        self.t8 = QtWidgets.QToolButton(self.frame_3)
        self.t8.setMinimumSize(QtCore.QSize(0, 30))
        self.t8.setStyleSheet("background-color:white;\n"
"border:none;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.t8.setObjectName("t8")
        self.gridLayout.addWidget(self.t8, 7, 1, 1, 1)
        self.t1 = QtWidgets.QToolButton(self.frame_3)
        self.t1.setMinimumSize(QtCore.QSize(0, 30))
        self.t1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.t1.setStyleSheet("background-color:white;\n"
"border:none;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.t1.setObjectName("t1")
        self.gridLayout.addWidget(self.t1, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setMinimumSize(QtCore.QSize(0, 45))
        self.back.setStyleSheet("QPushButton{\n"
"color:white;\n"
"    background-color: rgb(0, 85, 255);\n"
"border:none;\n"
"font: 23pt \"Azonix\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"color:black;\n"
"\n"
"}")
        self.back.setObjectName("back")
        self.verticalLayout.addWidget(self.back)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Settings"))
        self.general.setText(_translate("MainWindow", "General"))
        self.personal_info.setText(_translate("MainWindow", "Personal Info"))
        self.Ai_info.setText(_translate("MainWindow", "A.I Info"))
        self.Premium.setText(_translate("MainWindow", "Premium+"))
        self.programs.setText(_translate("MainWindow", "Programs"))
        self.heading.setText(_translate("MainWindow", "File locations will be used to open programs"))
        self.t5.setText(_translate("MainWindow", "..."))
        self.t4.setText(_translate("MainWindow", "..."))
        self.t7.setText(_translate("MainWindow", "..."))
        self.t3.setText(_translate("MainWindow", "..."))
        self.t2.setText(_translate("MainWindow", "..."))
        self.t6.setText(_translate("MainWindow", "..."))
        self.t8.setText(_translate("MainWindow", "..."))
        self.t1.setText(_translate("MainWindow", "..."))
        self.back.setText(_translate("MainWindow", "Back"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_file_location()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
