# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings-general_responsive.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont,QFontDatabase

class General(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 653)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bgImage/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.958968)
        QFontDatabase.addApplicationFont(':/bgImage/Azonix-1VB0.otf')
        QFontDatabase.addApplicationFont(':/bgImage/pdark.ttf')
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:black;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menu = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menu)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.menu)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"font: 14pt \"Azonix\";\n"
"background-color:transparent;\n"
"border:2px solid transparent;\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"padding:10px 10px\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignTop)
        self.pushButton_2 = QtWidgets.QPushButton(self.menu)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"font: 14pt \"Azonix\";\n"
"background-color:transparent;\n"
"border:2px solid transparent;\n"
"border-bottom-color:white;\n"
"color:white;\n"
"padding:10px 10px\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignTop)
        self.pushButton_3 = QtWidgets.QPushButton(self.menu)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"font: 14pt \"Azonix\";\n"
"background-color:transparent;\n"
"border:2px solid transparent;\n"
"color:white;\n"
"border-bottom-color: white;;\n"
"padding:10px 10px\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignTop)
        self.pushButton_5 = QtWidgets.QPushButton(self.menu)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"font: 14pt \"Azonix\";\n"
"background-color:transparent;\n"
"border:2px solid transparent;\n"
"border-bottom-color:white;\n"
"color:white;\n"
"padding:10px 10px\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignTop)
        self.pushButton_6 = QtWidgets.QPushButton(self.menu)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"font: 14pt \"Azonix\";\n"
"background-color:transparent;\n"
"border:2px solid transparent;\n"
"border-bottom-color:white;\n"
"color:white;\n"
"padding:10px 10px\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.menu)
        self.represent_info = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.represent_info.sizePolicy().hasHeightForWidth())
        self.represent_info.setSizePolicy(sizePolicy)
        self.represent_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.represent_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.represent_info.setObjectName("represent_info")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.represent_info)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.represent_info)
        self.label_4.setEnabled(True)
        self.label_4.setMinimumSize(QtCore.QSize(20, 0))
        self.label_4.setMaximumSize(QtCore.QSize(20, 20))
        self.label_4.setStyleSheet("background-color:cyan;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(self.represent_info)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 34pt \"MS Shell Dlg 2\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.represent_info)
        self.label_6.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"color:white;\n"
"background-color:transparent;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.represent_info)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 34pt \"MS Shell Dlg 2\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_5 = QtWidgets.QLabel(self.represent_info)
        self.label_5.setMaximumSize(QtCore.QSize(30, 30))
        self.label_5.setStyleSheet("color:white;\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"background-color:transparent;")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout.addWidget(self.represent_info, 0, QtCore.Qt.AlignTop)
        self.checkboxes_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkboxes_frame.sizePolicy().hasHeightForWidth())
        self.checkboxes_frame.setSizePolicy(sizePolicy)
        self.checkboxes_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.checkboxes_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.checkboxes_frame.setObjectName("checkboxes_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.checkboxes_frame)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setSpacing(43)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.checkboxes_frame)
        self.checkBox.setStyleSheet("QCheckBox {\n"
"    spacing: 5px;\n"
"    font: 25pt \"Azonix\";\n"
"    color:white;\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background:rectangle white;;\n"
"    height:30px;\n"
"    width:30px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    height:30px;\n"
"    width:30px;\n"
"    background-color:cyan;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    height:30px;\n"
"    width:30px;\n"
"    background-color:black;\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:indeterminate:pressed {\n"
"    height:30px;\n"
"    width:30px;\n"
"    background-color:blue;\n"
"}\n"
"\n"
"")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.checkboxes_frame)
        self.checkBox_2.setStyleSheet("QCheckBox {\n"
"    spacing: 5px;\n"
"    font: 25pt \"Azonix\";\n"
"    color:white;\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background:rectangle white;;\n"
"    height:30px;\n"
"    width:30px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    height:30px;\n"
"    width:30px;\n"
"    background-color:cyan;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    height:30px;\n"
"    width:30px;\n"
"    background-color:black;\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:indeterminate:pressed {\n"
"    height:30px;\n"
"    width:30px;\n"
"    background-color:blue;\n"
"}\n"
"\n"
"")
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.checkboxes_frame)
        self.checkBox_3.setStyleSheet("QCheckBox {\n"
"    spacing: 5px;\n"
"    font: 15pt \"Azonix\";\n"
"    color:white;\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background:rectangle white;;\n"
"    height:30px;\n"
"    width:30px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    height:30px;\n"
"    width:30px;\n"
"    background-color:cyan;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    height:30px;\n"
"    width:30px;\n"
"    background-color:black;\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:indeterminate:pressed {\n"
"    height:30px;\n"
"    width:30px;\n"
"    background-color:blue;\n"
"}\n"
"\n"
"")
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.verticalLayout.addWidget(self.checkboxes_frame, 0, QtCore.Qt.AlignTop)
        self.totorial_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totorial_frame.sizePolicy().hasHeightForWidth())
        self.totorial_frame.setSizePolicy(sizePolicy)
        self.totorial_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totorial_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totorial_frame.setObjectName("totorial_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.totorial_frame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.totorial_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"font: 24pt \"Azonix\";\n"
"background-color: rgb(0, 76, 255);\n"
"border:2px solid transparent;\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"color:black;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.label = QtWidgets.QLabel(self.totorial_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 30pt \"MS Shell Dlg 2\";\n"
"background-color:transparent;\n"
"color:white;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout.addWidget(self.totorial_frame)
        self.hotkeys_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hotkeys_frame.sizePolicy().hasHeightForWidth())
        self.hotkeys_frame.setSizePolicy(sizePolicy)
        self.hotkeys_frame.setMinimumSize(QtCore.QSize(10, 0))
        self.hotkeys_frame.setMaximumSize(QtCore.QSize(950, 400))
        self.hotkeys_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hotkeys_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hotkeys_frame.setObjectName("hotkeys_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.hotkeys_frame)
        self.horizontalLayout_3.setContentsMargins(48, -1, 48, -1)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.hotkeys_frame)
        self.label_2.setStyleSheet("font: 20pt \"Azonix\";\n"
"background-color:transparent;\n"
"color:white;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.hotkeys_frame)
        self.lineEdit_3.setStyleSheet("border-image: url(:/bgImage/ui_elementbox4.png);\n"
"background-color:transparent;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color:white;\n"
"padding:35px 60px")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.label_3 = QtWidgets.QLabel(self.hotkeys_frame)
        self.label_3.setStyleSheet("font: 24pt \"Azonix\";\n"
"background-color:transparent;\n"
"color:white;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.hotkeys_frame)
        self.lineEdit_2.setStyleSheet("border-image: url(:/bgImage/ui_elementbox3.png);\n"
"border-image: url(:/bgImage/ui_elementbox4.png);\n"
"background-color:transparent;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color:white;\n"
"padding:35px 48px;")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout.addWidget(self.hotkeys_frame, 0, QtCore.Qt.AlignBottom)
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setMinimumSize(QtCore.QSize(0, 55))
        self.back.setMaximumSize(QtCore.QSize(16777215, 500))
        self.back.setStyleSheet("QPushButton{\n"
"font: 24pt \"Azonix\";\n"
"background-color: rgb(0, 76, 255);\n"
"border:2px solid transparent;\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"color:black;\n"
"}")
        self.back.setObjectName("back")
        self.verticalLayout.addWidget(self.back)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Settings"))
        self.pushButton.setText(_translate("MainWindow", "General"))
        self.pushButton_2.setText(_translate("MainWindow", "Personal Info"))
        self.pushButton_3.setText(_translate("MainWindow", "A.I Info"))
        self.pushButton_5.setText(_translate("MainWindow", "Premium+"))
        self.pushButton_6.setText(_translate("MainWindow", "Programs"))
        self.label_7.setText(_translate("MainWindow", "-"))
        self.label_6.setText(_translate("MainWindow", "Represents"))
        self.label_8.setText(_translate("MainWindow", "-"))
        self.label_5.setText(_translate("MainWindow", "  ✓"))
        self.checkBox.setText(_translate("MainWindow", "  Welcome Message"))
        self.checkBox_2.setText(_translate("MainWindow", "  Goodbye Message"))
        self.checkBox_3.setText(_translate("MainWindow", "  Show confirmation dialog box when closing ZERA"))
        self.pushButton_7.setText(_translate("MainWindow", "Reset"))
        self.label.setText(_translate("MainWindow", "<strong>Hotkeys"))
        self.label_2.setText(_translate("MainWindow", "Wake up"))
        self.lineEdit_3.setText(_translate("MainWindow", "Tab"))
        self.label_3.setText(_translate("MainWindow", "Sleep"))
        self.lineEdit_2.setText(_translate("MainWindow", "Home"))
        self.back.setText(_translate("MainWindow", "Back"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = General()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
