# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings-Ai_info_responsive.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont,QFontDatabase

class Ui_ai_info(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 726)
        # MainWindow.setMinimumSize(QtCore.QSize(760, 726))
        # MainWindow.setMaximumSize(QtCore.QSize(766, 726))
        QFontDatabase.addApplicationFont(':/bgImage/Azonix-1VB0.otf')
        QFontDatabase.addApplicationFont(':/bgImage/pdark.ttf')
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bgImage/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.965456)
        MainWindow.setStyleSheet("background-color:black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menu = QtWidgets.QFrame(self.centralwidget)
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menu)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.menu)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"font: 14pt \"Azonix\";\n"
"background-color:transparent;\n"
"border:2px solid transparent;\n"
"border-bottom-color:white;\n"
"color:white;\n"
"padding:10px 10px\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.menu)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"font: 14pt \"Azonix\";\n"
"background-color:transparent;\n"
"border:2px solid transparent;\n"
"border-bottom-color:white;\n"
"color:white;\n"
"padding:10px 10px\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.menu)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"font: 14pt \"Azonix\";\n"
"background-color:transparent;\n"
"border:2px solid transparent;\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"padding:10px 10px\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.menu)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"font: 14pt \"Azonix\";\n"
"background-color:transparent;\n"
"border:2px solid transparent;\n"
"border-bottom-color:white;\n"
"color:white;\n"
"padding:10px 10px\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.menu)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"font: 14pt \"Azonix\";\n"
"background-color:transparent;\n"
"border:2px solid transparent;\n"
"border-bottom-color:white;\n"
"color:white;\n"
"padding:10px 10px\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.verticalLayout.addWidget(self.menu, 0, QtCore.Qt.AlignTop)
        self.body = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.body.sizePolicy().hasHeightForWidth())
        self.body.setSizePolicy(sizePolicy)
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name = QtWidgets.QFrame(self.body)
        self.name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name.setObjectName("name")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.name)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.name)
        self.label.setStyleSheet("color:white;\n"
"font: 20pt \"Azonix\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.name, 0, QtCore.Qt.AlignTop)
        self.image = QtWidgets.QFrame(self.body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image.setObjectName("image")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.image)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.image)
        self.label_3.setMaximumSize(QtCore.QSize(172, 179))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/bgImage/user_pic.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.image)
        self.body_2 = QtWidgets.QFrame(self.body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.body_2.sizePolicy().hasHeightForWidth())
        self.body_2.setSizePolicy(sizePolicy)
        self.body_2.setStyleSheet("border-image: url(:/bgImage/ui_elementbox5.png);")
        self.body_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_2.setObjectName("body_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.body_2)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 39)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.body_2)
        self.frame_4.setStyleSheet("border-image:none;\n"
"background-color:transparent;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(-1, 55, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setStyleSheet("font: 20pt \"Azonix\";\n"
"color:white;\n"
"background-color:transparent;\n"
"padding:10px 1px;\n"
"border-image:none;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_4.setStyleSheet("font: 20pt \"Azonix\";\n"
"color:white;\n"
"background-color:transparent;\n"
"border-image:none;")
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_4.addWidget(self.radioButton_4)
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_3.setStyleSheet("font: 20pt \"Azonix\";\n"
"color:white;\n"
"background-color:transparent;\n"
"border-image:none;")
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_4.addWidget(self.radioButton_3)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.body_2)
        self.frame_5.setStyleSheet("border-image:none;\n"
"background-color:transparent;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(83, -1, 62, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setStyleSheet("font: 20pt \"Azonix\";\n"
"color:white;\n"
"background-color:transparent;\n"
"padding:20px 1px;\n"
"background-color:transparent;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.comboBox = QtWidgets.QComboBox(self.frame_5)
        self.comboBox.setMaximumSize(QtCore.QSize(233, 16777215))
        self.comboBox.setStyleSheet("QComboBox{\n"
"color: white;\n"
"border:2px solid rgb(0, 155, 233);\n"
"padding:10px 10px;\n"
"background-color:transparent;\n"
"color:white;\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"}\n"
"QListView{\n"
"color:white;\n"
"border:2px solid rgb(0, 155, 233);\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.body_2)
        self.frame_6.setStyleSheet("border-image:none;\n"
"background-color:transparent;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(-1, 0, 350, 17)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setStyleSheet("font: 20pt \"Azonix\";\n"
"color:white;\n"
"background-color:transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.body_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("border-image:none;\n"
"background-color:transparent;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setContentsMargins(-1, 9, 108, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setStyleSheet("font: 20pt \"Azonix\";\n"
"color:white;\n"
"background-color:transparent;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_3.addWidget(self.frame_7, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_2.addWidget(self.body_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.body)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"color:white;\n"
"font: 18pt \"Azonix\";\n"
"background-color: rgb(0, 72, 218);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:white;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AI info"))
        self.pushButton.setText(_translate("MainWindow", "General"))
        self.pushButton_2.setText(_translate("MainWindow", "Personal Info"))
        self.pushButton_3.setText(_translate("MainWindow", "A.I Info"))
        self.pushButton_5.setText(_translate("MainWindow", "Premium+"))
        self.pushButton_6.setText(_translate("MainWindow", "Programs"))
        self.label.setText(_translate("MainWindow", "Zera"))
        self.label_6.setText(_translate("MainWindow", "A.I :-"))
        self.radioButton_4.setText(_translate("MainWindow", "ZERA"))
        self.radioButton_3.setText(_translate("MainWindow", "Jarvis"))
        self.label_9.setText(_translate("MainWindow", "Available voices :-"))
        # self.comboBox.setItemText(0, _translate("MainWindow", "voice1"))
        # self.comboBox.setItemText(1, _translate("MainWindow", "voice2"))
        # self.comboBox.setItemText(2, _translate("MainWindow", "voice3"))
        self.label_2.setText(_translate("MainWindow", "A.I age :- 22"))
        self.label_4.setText(_translate("MainWindow", "Developer :- Yash Akarsh"))
        self.pushButton_4.setText(_translate("MainWindow", "Back"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ai_info()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
