# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings-Personal_info_responsive.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont,QFontDatabase

class Ui_PersonalInfo(object):
    def setupUi(self, PersonalInfo):
        PersonalInfo.setObjectName("PersonalInfo")
        PersonalInfo.resize(753, 631)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bgImage/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PersonalInfo.setWindowIcon(icon)
        PersonalInfo.setWindowOpacity(0.957667)
        PersonalInfo.setStyleSheet("background-color:black;")
        QFontDatabase.addApplicationFont(':/bgImage/Azonix-1VB0.otf')
        QFontDatabase.addApplicationFont(':/bgImage/pdark.ttf')
        self.centralwidget = QtWidgets.QWidget(PersonalInfo)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.general = QtWidgets.QPushButton(self.frame_2)
        self.general.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.general.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 14pt \"Azonix\";\n"
"    color:white;\n"
"padding:10px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.general.setObjectName("general")
        self.horizontalLayout.addWidget(self.general, 0, QtCore.Qt.AlignTop)
        self.personal_info = QtWidgets.QPushButton(self.frame_2)
        self.personal_info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.personal_info.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:rgb(0, 111, 167);\n"
"    font: 14pt \"Azonix\";\n"
"    color:rgb(0, 111, 167);\n"
"padding:10px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}\n"
"")
        self.personal_info.setObjectName("personal_info")
        self.horizontalLayout.addWidget(self.personal_info, 0, QtCore.Qt.AlignTop)
        self.Ai_info = QtWidgets.QPushButton(self.frame_2)
        self.Ai_info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Ai_info.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 14pt \"Azonix\";\n"
"    color:white;\n"
"padding:10px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.Ai_info.setObjectName("Ai_info")
        self.horizontalLayout.addWidget(self.Ai_info, 0, QtCore.Qt.AlignTop)
        self.Premium = QtWidgets.QPushButton(self.frame_2)
        self.Premium.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Premium.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 14pt \"Azonix\";\n"
"    color:white;\n"
"padding:10px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.Premium.setObjectName("Premium")
        self.horizontalLayout.addWidget(self.Premium, 0, QtCore.Qt.AlignTop)
        self.credits = QtWidgets.QPushButton(self.frame_2)
        self.credits.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.credits.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 14pt \"Azonix\";\n"
"    color:white;\n"
"padding:10px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.credits.setObjectName("credits")
        self.horizontalLayout.addWidget(self.credits, 0, QtCore.Qt.AlignTop)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.name = QtWidgets.QLabel(self.frame_3)
        self.name.setMinimumSize(QtCore.QSize(250, 77))
        self.name.setMaximumSize(QtCore.QSize(200, 16777215))
        self.name.setStyleSheet("font: 15pt \"Azonix\";\n"
"color:white;\n"
"background-color:transparent;\n"
"border-image: url(:/bgImage/ui_elementbox4.png);")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.horizontalLayout_2.addWidget(self.name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.name_area = QtWidgets.QLineEdit(self.frame_3)
        self.name_area.setMinimumSize(QtCore.QSize(0, 80))
        self.name_area.setStyleSheet("font: 14pt \"Azonix\";\n"
"border-image: url(:/bgImage/ui_elementbox5.png);\n"
"background-color:transparent;\n"
"color:white;\n"
"padding:23px")
        self.name_area.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_area.setObjectName("name_area")
        self.horizontalLayout_2.addWidget(self.name_area)
        self.gridLayout_2.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.DOB = QtWidgets.QLabel(self.frame_4)
        self.DOB.setMinimumSize(QtCore.QSize(260, 100))
        self.DOB.setStyleSheet("font: 13pt \"Azonix\";\n"
"color:white;\n"
"background-color:transparent;\n"
"border-image: url(:/bgImage/ui_elementbox4.png);")
        self.DOB.setAlignment(QtCore.Qt.AlignCenter)
        self.DOB.setObjectName("DOB")
        self.horizontalLayout_3.addWidget(self.DOB)
        spacerItem1 = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.name_area_2 = QtWidgets.QLineEdit(self.frame_4)
        self.name_area_2.setMinimumSize(QtCore.QSize(0, 80))
        self.name_area_2.setStyleSheet("font: 14pt \"Azonix\";\n"
"border-image: url(:/bgImage/ui_elementbox5.png);\n"
"background-color:transparent;\n"
"color:white;\n"
"padding:23px")
        self.name_area_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_area_2.setObjectName("name_area_2")
        self.horizontalLayout_3.addWidget(self.name_area_2)
        self.gridLayout_2.addWidget(self.frame_4, 2, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Email = QtWidgets.QLabel(self.frame_5)
        self.Email.setMinimumSize(QtCore.QSize(250, 100))
        self.Email.setMaximumSize(QtCore.QSize(250, 16777215))
        self.Email.setStyleSheet("font: 14pt \"Azonix\";\n"
"color:white;\n"
"background-color:transparent;\n"
"border-image: url(:/bgImage/ui_elementbox4.png);\n"
"padding:5px;")
        self.Email.setAlignment(QtCore.Qt.AlignCenter)
        self.Email.setObjectName("Email")
        self.horizontalLayout_4.addWidget(self.Email)
        spacerItem2 = QtWidgets.QSpacerItem(142, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.name_area_3 = QtWidgets.QLineEdit(self.frame_5)
        self.name_area_3.setMinimumSize(QtCore.QSize(0, 80))
        self.name_area_3.setStyleSheet("font: 14pt \"Azonix\";\n"
"border-image: url(:/bgImage/ui_elementbox5.png);\n"
"background-color:transparent;\n"
"color:white;\n"
"padding:23px")
        self.name_area_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_area_3.setObjectName("name_area_3")
        self.horizontalLayout_4.addWidget(self.name_area_3)
        self.gridLayout_2.addWidget(self.frame_5, 3, 0, 1, 1)
        self.note = QtWidgets.QLabel(self.frame)
        self.note.setAcceptDrops(False)
        self.note.setAutoFillBackground(False)
        self.note.setStyleSheet("font: 14pt \"Azonix\";\n"
"color:white;\n"
"background-color:transparent;")
        self.note.setScaledContents(False)
        self.note.setAlignment(QtCore.Qt.AlignCenter)
        self.note.setObjectName("note")
        self.gridLayout_2.addWidget(self.note, 4, 0, 1, 1)
        self.back = QtWidgets.QPushButton(self.frame)
        self.back.setMinimumSize(QtCore.QSize(0, 50))
        self.back.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 85, 255);\n"
"border:none;\n"
"font: 18pt \"Azonix\";\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"color:black;\n"
"background-color:white;\n"
"\n"
"}\n"
"")
        self.back.setObjectName("back")
        self.gridLayout_2.addWidget(self.back, 5, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        PersonalInfo.setCentralWidget(self.centralwidget)

        self.retranslateUi(PersonalInfo)
        QtCore.QMetaObject.connectSlotsByName(PersonalInfo)

    def retranslateUi(self, PersonalInfo):
        _translate = QtCore.QCoreApplication.translate
        PersonalInfo.setWindowTitle(_translate("PersonalInfo", "Settings"))
        self.general.setText(_translate("PersonalInfo", "General"))
        self.personal_info.setText(_translate("PersonalInfo", "Personal Info"))
        self.Ai_info.setText(_translate("PersonalInfo", "A.I Info"))
        self.Premium.setText(_translate("PersonalInfo", "Premium+"))
        self.credits.setText(_translate("PersonalInfo", "Programs"))
        self.name.setText(_translate("PersonalInfo", "Name"))
        self.DOB.setText(_translate("PersonalInfo", "Date of birth"))
        self.Email.setText(_translate("PersonalInfo", "Email"))
        self.note.setText(_translate("PersonalInfo", "Note : - The data saved will be used by the A.I."))
        self.back.setText(_translate("PersonalInfo", "Back"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PersonalInfo = QtWidgets.QMainWindow()
    ui = Ui_PersonalInfo()
    ui.setupUi(PersonalInfo)
    PersonalInfo.show()
    sys.exit(app.exec_())
