# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings-premium_responsive.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont,QFontDatabase

class Premium(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 637)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        QFontDatabase.addApplicationFont(':/bgImage/Azonix-1VB0.otf')
        QFontDatabase.addApplicationFont(':/bgImage/pdark.ttf')
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bgImage/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowOpacity(0.97)
        MainWindow.setStyleSheet("background-color:black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.general = QtWidgets.QPushButton(self.frame_2)
        self.general.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.general.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 14pt \"Azonix\";\n"
"    color:white;\n"
"padding:10px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.general.setObjectName("general")
        self.horizontalLayout.addWidget(self.general, 0, QtCore.Qt.AlignTop)
        self.personal_info = QtWidgets.QPushButton(self.frame_2)
        self.personal_info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.personal_info.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 14pt \"Azonix\";\n"
"    color:white;\n"
"padding:10px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}\n"
"")
        self.personal_info.setObjectName("personal_info")
        self.horizontalLayout.addWidget(self.personal_info, 0, QtCore.Qt.AlignTop)
        self.Ai_info = QtWidgets.QPushButton(self.frame_2)
        self.Ai_info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Ai_info.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 14pt \"Azonix\";\n"
"    color:white;\n"
"padding:10px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.Ai_info.setObjectName("Ai_info")
        self.horizontalLayout.addWidget(self.Ai_info, 0, QtCore.Qt.AlignTop)
        self.Premium = QtWidgets.QPushButton(self.frame_2)
        self.Premium.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Premium.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 14pt \"Azonix\";\n"
"    color:white;\n"
"padding:10px;\n"
"color:rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.Premium.setObjectName("Premium")
        self.horizontalLayout.addWidget(self.Premium, 0, QtCore.Qt.AlignTop)
        self.credits = QtWidgets.QPushButton(self.frame_2)
        self.credits.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.credits.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 14pt \"Azonix\";\n"
"    color:white;\n"
"padding:10px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 111, 167);\n"
"border-bottom-color: rgb(0, 111, 167);\n"
"}")
        self.credits.setObjectName("credits")
        self.horizontalLayout.addWidget(self.credits, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Heading = QtWidgets.QLabel(self.frame)
        self.Heading.setStyleSheet("QLabel{\n"
"    font: 22pt \"Azonix\";\n"
"color:white;\n"
"    \n"
"background-color: transparent\n"
"}")
        self.Heading.setAlignment(QtCore.Qt.AlignCenter)
        self.Heading.setObjectName("Heading")
        self.horizontalLayout_2.addWidget(self.Heading)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 49)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Features_label = QtWidgets.QLabel(self.frame_3)
        self.Features_label.setStyleSheet("QLabel{\n"
"color:white;\n"
"background-color:transparent;\n"
"    font: 22pt \"Azonix\";\n"
"}")
        self.Features_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Features_label.setObjectName("Features_label")
        self.horizontalLayout_3.addWidget(self.Features_label)
        self.verticalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignTop)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setSpacing(45)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.point1 = QtWidgets.QLabel(self.frame_4)
        self.point1.setStyleSheet("QLabel{\n"
"color: white;\n"
"background-color: transparent;\n"
"    font: 15pt \"Azonix\";\n"
"}\n"
"")
        self.point1.setObjectName("point1")
        self.verticalLayout_2.addWidget(self.point1)
        self.point2 = QtWidgets.QLabel(self.frame_4)
        self.point2.setStyleSheet("QLabel{\n"
"color: white;\n"
"background-color: transparent;\n"
"    font: 15pt \"Azonix\";\n"
"}")
        self.point2.setObjectName("point2")
        self.verticalLayout_2.addWidget(self.point2)
        self.point3 = QtWidgets.QLabel(self.frame_4)
        self.point3.setStyleSheet("QLabel{\n"
"color: white;\n"
"background-color: transparent;\n"
"    font: 15pt \"Azonix\";\n"
"}")
        self.point3.setObjectName("point3")
        self.verticalLayout_2.addWidget(self.point3)
        self.point4 = QtWidgets.QLabel(self.frame_4)
        self.point4.setStyleSheet("QLabel{\n"
"color:white;\n"
"background-color: transparent;\n"
"    font: 15pt \"Azonix\";\n"
"}")
        self.point4.setObjectName("point4")
        self.verticalLayout_2.addWidget(self.point4)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 40)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.version = QtWidgets.QLabel(self.frame_5)
        self.version.setMinimumSize(QtCore.QSize(100, 60))
        self.version.setMaximumSize(QtCore.QSize(500, 16777215))
        self.version.setStyleSheet("QLabel{\n"
"    border-image: url(:/bgImage/ui_elementbox5.png);\n"
"color:white;\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: transparent\n"
"}")
        self.version.setScaledContents(False)
        self.version.setAlignment(QtCore.Qt.AlignCenter)
        self.version.setObjectName("version")
        self.horizontalLayout_4.addWidget(self.version)
        self.verticalLayout.addWidget(self.frame_5)
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setMinimumSize(QtCore.QSize(0, 40))
        self.back.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 85, 255);\n"
"border:none;\n"
"color:white;\n"
"    font: 20pt \"Azonix\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"color:black;\n"
"}")
        self.back.setObjectName("back")
        self.verticalLayout.addWidget(self.back)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Settings"))
        self.general.setText(_translate("MainWindow", "General"))
        self.personal_info.setText(_translate("MainWindow", "Personal Info"))
        self.Ai_info.setText(_translate("MainWindow", "A.I Info"))
        self.Premium.setText(_translate("MainWindow", "Premium+"))
        self.credits.setText(_translate("MainWindow", "Programs"))
        self.Heading.setText(_translate("MainWindow", "Premium Plus+ - Ultimate Edition"))
        self.Features_label.setText(_translate("MainWindow", "Features"))
        self.point1.setText(_translate("MainWindow", "+ YOU HAVE ACCESS FOR JARVIS AND ZERA."))
        self.point2.setText(_translate("MainWindow", "+ YOU HAVE ACCESS FOR EVERYTHING ON THE HOME PAGE."))
        self.point3.setText(_translate("MainWindow", "+ YOU CAN GIVE COMMANDS BY TYPING. (Next Update) "))
        self.point4.setText(_translate("MainWindow", "+ say \"what are your features\" to get all the features."))
        self.version.setText(_translate("MainWindow", "Version : 3.0.0.0"))
        self.back.setText(_translate("MainWindow", "Back"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Premium()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
