# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont,QFontDatabase

import ctypes
# hiding the window
ctypes.windll.user32.ShowWindow( ctypes.windll.kernel32.GetConsoleWindow(), 0 )

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(485, 639)
        MainWindow.setStyleSheet("color:white;\n"
"background-image: url(:/bgImage/bg-alter.png);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bgImage/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        QFontDatabase.addApplicationFont(':/bgImage/Azonix-1VB0.otf')
        QFontDatabase.addApplicationFont(':/bgImage/pdark.ttf')
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("background:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dob_text = QtWidgets.QLabel(self.frame_3)
        self.dob_text.setStyleSheet("font: 15pt \"Azonix\";\n"
"color:white;\n"
"padding:0px 15px;")
        self.dob_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dob_text.setObjectName("dob_text")
        self.verticalLayout_3.addWidget(self.dob_text)
        self.dob = QtWidgets.QDateEdit(self.frame_3)
        self.dob.setStyleSheet("QDateEdit\n"
"{\n"
"    background-color: transparent;\n"
"       border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 18pt \"Azonix\";\n"
"    border-bottom-left-radius:20px;\n"
"padding:10px 20px;\n"
"}")
        self.dob.setObjectName("dob")
        self.verticalLayout_3.addWidget(self.dob)
        self.gridLayout.addWidget(self.frame_3, 2, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("background:none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 34)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.email = QtWidgets.QLineEdit(self.frame_6)
        self.email.setStyleSheet("QLineEdit{\n"
"font: 18pt \"Azonix\";\n"
"background-color:transparent;\n"
"border:2px solid transparent;\n"
"border-bottom-color:white;\n"
"border-bottom-left-radius:20px;\n"
"padding:10px 20px;\n"
"}")
        self.email.setObjectName("email")
        self.verticalLayout_5.addWidget(self.email)
        self.gridLayout.addWidget(self.frame_6, 5, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.heading = QtWidgets.QLabel(self.frame)
        self.heading.setStyleSheet("font: 45pt \"Azonix\";")
        self.heading.setAlignment(QtCore.Qt.AlignCenter)
        self.heading.setObjectName("heading")
        self.verticalLayout.addWidget(self.heading)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.username = QtWidgets.QLineEdit(self.frame_2)
        self.username.setMaximumSize(QtCore.QSize(350, 16777215))
        self.username.setStyleSheet("QLineEdit{\n"
"font: 18pt \"Azonix\";\n"
"background-color:transparent;\n"
"border:2px solid transparent;\n"
"border-bottom-color:white;\n"
"border-bottom-left-radius:20px;\n"
"padding:10px 20px;\n"
"}")
        self.username.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.username.setObjectName("username")
        self.verticalLayout_6.addWidget(self.username)
        self.gridLayout.addWidget(self.frame_2, 1, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setStyleSheet("background:none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.age_text = QtWidgets.QLabel(self.frame_4)
        self.age_text.setStyleSheet("font: 15pt \"Azonix\";\n"
"padding:0 15px;")
        self.age_text.setObjectName("age_text")
        self.verticalLayout_4.addWidget(self.age_text)
        self.AgeSelection = QtWidgets.QSpinBox(self.frame_4)
        self.AgeSelection.setStyleSheet("QSpinBox\n"
"{\n"
"    background-color: transparent;\n"
"       border:2px solid transparent;\n"
"    border-bottom-color:white;\n"
"    font: 18pt \"Azonix\";\n"
"border-bottom-left-radius:20px;\n"
"padding:10px 20px;\n"
"}")
        self.AgeSelection.setObjectName("AgeSelection")
        self.verticalLayout_4.addWidget(self.AgeSelection)
        self.gridLayout.addWidget(self.frame_4, 3, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setStyleSheet("background:none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setContentsMargins(-1, 38, -1, -1)
        self.horizontalLayout.setSpacing(29)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.male = QtWidgets.QRadioButton(self.frame_5)
        self.male.setStyleSheet("font: 17pt \"Azonix\";\n"
"padding:10px 20px;")
        self.male.setObjectName("male")
        self.horizontalLayout.addWidget(self.male)
        self.female = QtWidgets.QRadioButton(self.frame_5)
        self.female.setStyleSheet("font: 17pt \"Azonix\";\n"
"padding:10px 10px;")
        self.female.setObjectName("female")
        self.horizontalLayout.addWidget(self.female)
        self.gridLayout.addWidget(self.frame_5, 4, 1, 1, 1)
        self.finish = QtWidgets.QPushButton(self.centralwidget)
        self.finish.setMinimumSize(QtCore.QSize(0, 50))
        self.finish.setStyleSheet("QPushButton{\n"
"background:none;\n"
"background-color: rgb(0, 85, 255);\n"
"border:2px solid transparent;\n"
"font: 20pt \"Azonix\";\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"border:2px solid;\n"
"border-color: rgb(0, 0, 2);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"border:none;\n"
"\n"
"}")
        self.finish.setObjectName("finish")
        self.gridLayout.addWidget(self.finish, 6, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Setup"))
        self.dob_text.setText(_translate("MainWindow", "D.O.B"))
        self.email.setPlaceholderText(_translate("MainWindow", "Email Address"))
        self.heading.setText(_translate("MainWindow", "Setup"))
        self.username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.age_text.setText(_translate("MainWindow", "Age"))
        self.male.setText(_translate("MainWindow", "Male"))
        self.female.setText(_translate("MainWindow", "Female"))
        self.finish.setText(_translate("MainWindow", "Finish"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
